### ISSUE TITLE
When using Variable Payload/following the example of messaging recursive tupling occurs on to/from unpack_list

### ISSUE THREAD

**Issue by tmrupp** [Tribler/py-ipv8#1002]
given this code:

```
@vp_compile
class MyCVariablePayload(VariablePayload):
    format_list = ['I', 'H']
    names = ['field1', 'field2']

mcvp = MyCVariablePayload(1, 2)
print(mcvp)
mcvp2 = MyCVariablePayload.from_unpack_list(*mcvp.to_pack_list())
print(mcvp2)
mcvp3 = MyCVariablePayload.from_unpack_list(*mcvp2.to_pack_list())
print(mcvp3)
```

this is the output:
```
MyCVariablePayload
| field1: 1
| field2: 2
MyCVariablePayload
| field1: ('I', 1)
| field2: ('H', 2)
MyCVariablePayload
| field1: ('I', ('I', 1))
| field2: ('H', ('H', 2))
```

It is my understanding that the fields should shed their type values in the tuples on repack, or am I mistaken.

python3 --version
Python 3.8.5

Ubuntu

**Comment by qstokkink** [comment]
This is intended behavior. These packing and unpacking methods are only to be used with a `Serializer` to convert your payloads to and from a `bytes` string.

In most cases you don't want to call them directly. For example, this is the way you would use a serializer to pack and unpack a Payload `instance` to a bytes `data`:

https://github.com/Tribler/py-ipv8/blob/2faffe6fcc7945399d2f7d76996f2df9028b422f/ipv8/test/messaging/test_serialization.py#L148-L149

If you are working with an `Overlay`/`Community` you will have a local `Serializer` available to you (there is also a singleton called `default_serializer` exposed in `ipv8.messaging.serialization`). Even better, if you [register your message](https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial/#adding-messages) in a `Community` subclass you will never even have to touch the serializer manually.

I converted this issue from a bug to a question. Feel free to ask about this functionality until you're satisfied.

**Comment by tmrupp** [comment]
Thanks I think this is closed then
