### ISSUE TITLE
distributed bootstrap service

### ISSUE THREAD

**Issue by synctext** [Tribler/py-ipv8#101]
https://njal.la/list/?search=ip-v8

Accepted Payments
We accept payments via Bitcoin, Litecoin, Monero, DASH, Bitcoin Cash and PayPal.

Who's behind Njalla?
We're a team of committed internet activists and we're also involved in other privacy projects such as the IPredator VPN service. Some of us have also been involved in projects like The Pirate Bay and Piratbyrån to mention a few things. Or to keep it simple; we've got a long history and serious understanding of the issues of anonymity on the internets.

**Comment by qstokkink** [comment]
This would make for a fun project, but might be more relevant for the Tribler repository.
