### ISSUE TITLE
Py-IPv8 3.0 - Hidden Service v3 based protocol, quantum resistant cryptography, authentication encryption, and professional exit nodes

### ISSUE THREAD

**Issue by Destroyinator69420** [Tribler/py-ipv8#1021]
If you have based the hidden service protocol in py-ipv8 on hidden service protocol v2, then you must know that hidden service protocol v2 is insecure and contains multiple vulnerabilities. Another weakness threatening onion routers is Shor's algorithm, the encryption must be able to defend against it or py-ipv8 will be no more secure than a proxy.

Authentication encryption: if a message is tampered with, then it will not be forwarded

I highly suggest moving the exit nodes from ordinary peers to trust token miners that burn a certain amount of trust tokens of trust tokens per quarter to run the exit node, and can sell the trust tokens back to users of py-ipv8 for cryptocurrency. This will prevent Sybil attacks by requiring that a user stake a minimum amount of trust tokens, which will make spinning up thousands of exit nodes to spy on traffic expensive. It might be desirable to allow any amount of trust tokens burned beyond 64GB to earn interest up to certain amount, so long as the node has more than 99% uptime. You could call it verified exit nodes and give them an orange checkmark.

**Comment by qstokkink** [comment]
Thanks for sharing your concerns. We are already quite acutely aware of the developments and vulnerabilities regarding anonymization technologies (the team behind IPv8 consists of Masters of Science, PhD's and professors). I already answered our stance on Shor's algorithm in #1013. At any rate, regardless of Shor's algorithm: if a message is tampered with, then it will not be forwarded.

Regarding the second half of your message (the suggestion to move to token burning for exit nodes): this is out of the scope of IPv8. IPv8 is only a library of networking tools. Social interactions (including payments) are handled by Tribler. This is something we are actively developing and we have some issues open in Tribler for this (for example https://github.com/Tribler/tribler/issues/5587). This doesn't make your suggestion less valuable, this is just the wrong repository to discuss it.

I assume these pointers sufficiently address your concerns and suggestions, so I'll close this issue.
