### ISSUE TITLE
simulation_tutorial_2.py failure

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1024]
**Operating System and version**
Builder `bbq`

**Traceback and/or steps to reproduce**

https://jenkins-ci.tribler.org/job/ipv8/job/validate_documentation/85/console

```python
[FAILED] Traceback detected in simulation_tutorial_2.py
=== stdout ===

=== stderr ===
/usr/lib/python3/dist-packages/jinja2/utils.py:485: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/usr/lib/python3/dist-packages/jinja2/runtime.py:318: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
INFO:SimpleCommunity:I am peer 0, I know 0 peers...
INFO:SimpleCommunity:I am peer 1, I know 0 peers...
INFO:SimpleCommunity:I am peer 2, I know 0 peers...
INFO:SimpleCommunity:I am peer 3, I know 0 peers...
INFO:SimpleCommunity:I am peer 4, I know 0 peers...
INFO:SimpleCommunity:I am peer 5, I know 0 peers...
INFO:SimpleCommunity:I am peer 6, I know 0 peers...
INFO:SimpleCommunity:I am peer 7, I know 0 peers...
INFO:SimpleCommunity:I am peer 8, I know 0 peers...
INFO:SimpleCommunity:I am peer 9, I know 0 peers...
INFO:SimpleCommunity:I am peer 10, I know 0 peers...
INFO:SimpleCommunity:I am peer 11, I know 0 peers...
INFO:SimpleCommunity:I am peer 12, I know 0 peers...
INFO:SimpleCommunity:I am peer 13, I know 0 peers...
INFO:SimpleCommunity:I am peer 14, I know 0 peers...
INFO:SimpleCommunity:I am peer 15, I know 0 peers...
INFO:SimpleCommunity:I am peer 16, I know 0 peers...
INFO:SimpleCommunity:I am peer 17, I know 0 peers...
INFO:SimpleCommunity:I am peer 18, I know 0 peers...
INFO:SimpleCommunity:I am peer 19, I know 0 peers...
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./validate_examples.py", line 35, in validate_run
    exec(compile(module_contents, module_path, 'exec', dont_inherit=True, optimize=0), {})  # pylint: disable=W0122
  File "/home/jenkins/ci/workspace/ipv8/validate_documentation/pyipv8/doc/simulation/simulation_tutorial_2.py", line 69, in <module>
    loop.run_forever()
  File "/home/jenkins/ci/workspace/ipv8/validate_documentation/pyipv8/simulation/discrete_loop.py", line 41, in run_forever
    raise self._exc
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/jenkins/ci/workspace/ipv8/validate_documentation/pyipv8/ipv8/test/mocking/endpoint.py", line 40, in send
    raise AssertionError("Received data from unregistered address %s" % repr(socket_address))
AssertionError: Received data from unregistered address UDPv4Address(ip='145.94.62.182', port=45803)
```

**Comment by devos50** [comment]
It looks like there is a leakage in the bootstrap server logic. The IP address reported is the local IP of `bbq`. Since I've made these simulation tutorials, I'll have a look at it and try to reproduce it 👍

**Comment by qstokkink** [comment]
Taking a quick look at this, I notice you're not overwriting the `my_estimated_wan`, only the `my_estimated_lan`:

https://github.com/Tribler/py-ipv8/blob/5975dd54e1b91ae739a01e632f8a0efa0c15cb17/doc/simulation/simulation_tutorial_2.py#L53

In contrast, this is what MockIPv8 does to init the `AutoMockEndpoint`:

https://github.com/Tribler/py-ipv8/blob/e9943d0f4a6964af54d5c48baacbaf9b4a48af1c/ipv8/test/mocking/ipv8.py#L46-L47

This WAN estimate is only corrected to the fake endpoint WAN when the first message is received. This means that there is a small window where it will have an estimate for the machine WAN instead of the fake endpoint WAN.

My intuition is that this is causing the failure.

**Comment by qstokkink** [comment]
After a deeper look, it turned out to be the following (bear with me):

1. The `AutoMockEndpoint` uses the non-netiface version of the LAN address check (`_address_is_lan_without_netifaces`):

https://github.com/Tribler/py-ipv8/blob/ed368b725f506608bf19c2368660b3ba6a157a59/ipv8/test/mocking/endpoint.py#L59

2. The `Community` uses `address_is_lan` for its LAN address check.

https://github.com/Tribler/py-ipv8/blob/cd9f2809ba80f04854217383d4e79c6236a46579/ipv8/community.py#L234

These two different methods don't agree with each other all the time. In particular, the following line will deem all addresses starting with `127` to be LAN addresses (which `_address_is_lan_without_netifaces()` does not agree with):

https://github.com/Tribler/py-ipv8/blob/ed368b725f506608bf19c2368660b3ba6a157a59/ipv8/messaging/interfaces/endpoint.py#L271

What is causing the unknown address is the line after the `address_is_lan` check in the `Community` class:

https://github.com/Tribler/py-ipv8/blob/cd9f2809ba80f04854217383d4e79c6236a46579/ipv8/community.py#L236

This line alters the address to traverse the non-existent mocked LAN NAT. Of course, there is no NAT and this address is not allowed in our fake Internet. In turn, this crashes the endpoint.

However, simply switching `AddressTester` to `address_is_lan()` is not enough. The `address_is_lan()` depends on the `_local_interfaces` list being populated, which is lazy loaded. The full fix also requires `AddressTester` to populate the local interfaces using `_get_lan_address()`. However, this an lazy loaded for a reason (it's slow and expensive). In order to mitigate the impact of this, the `AddressTester` should become a singleton.
