### ISSUE TITLE
Broken links in all documentation

### ISSUE THREAD

**Issue by drew2a** [Tribler/py-ipv8#1041]
All links inside the ["Getting Started"](https://github.com/Tribler/py-ipv8#getting-started) section are broken:

![image](https://user-images.githubusercontent.com/13798583/135293284-f04615fa-c90e-4e3a-ac21-f27194fd7c1d.png)

![image](https://user-images.githubusercontent.com/13798583/135293364-064f8acc-dceb-4f35-9d2f-0b8d030120b4.png)

**Comment by qstokkink** [comment]
It's not just the README, all links on the ReadTheDocs are now broken. This happened before in #659: ReadTheDocs must have changed something again. All relative links will have to be updated.
