### ISSUE TITLE
IPv8 & Tribler tests hangs when there is a network interface with mask `0.0.0.0`

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/py-ipv8#1057]
Yesterday core tests for Tribler stop working on my Windows machine. Some tests pass, but most of them hang and then terminate on timeout.

As it turns out, problem is in [`AutoMockEndpoint._generate_unique_address`](https://github.com/Tribler/py-ipv8/blob/fcf2c7971a9b3d91c4dfb159f6e17f68c081f1d0/ipv8/test/mocking/endpoint.py#L118) method:

```python
    def _generate_unique_address(self):
        address = self._generate_address()

        while address in internet or self._is_lan(address):
            address = self._generate_address()

        return address
```

This while loop inside the method works as an infinite loop. The reason for this bug is that one of the network interfaces has netmask `0.0.0.0`:

```python
>>> import netifaces
>>> netifaces.interfaces()
['{E98500B3-F5E4-F4C1-6D2B-5D3145D2B1AC}', '{76452E84-E598-4A0E-B612-6CBD22E518D8}', '{12FC1DF3-FDF1-44FD-BDD1-6562A0165CB1}', '{DE130FDB-E5EB-4E5A-A08E-C51F158183A4}', '{ED752F61-E6C3-11EA-9AF0-806E6F6E6963}']
>>> netifaces.ifaddresses('{E98500B3-F5E4-F4C1-6D2B-5D3145D2B1AC}')
{-1000: [{'addr': ''}], 2: [{'addr': '10.0.0.2', 'netmask': '0.0.0.0', 'broadcast': '255.255.255.255'}]}
```

When the `AutoMockEndpoint._is_lan(address)` method executes inside a loop, it compares a new random IP address with a local interface IP address. It applies the netmask `0.0.0.0` to both addresses reducing them to two zeroes, then compares two zeroes and concludes that the new random IP address belongs to this local network. So,  `_generate_unique_address` get stuck in an infinite loop because every random IP address is considered belonging to a local network with mask `0.0.0.0`.

When a network interface has mask `0.0.0.0`, it means that [the network interface isn't bound to any network at all; not even localhost requests will be acknowledged. If anything, it's a way of the operating system to present the interface as available but inactive and un-routed](https://superuser.com/questions/305850/what-does-mask-0-0-0-0-mean-when-its-assigned-to-a-network-interface).

I think the `EndpointListener._get_interface_addresses` method should skip interfaces with mask `0.0.0.0`; it should solve the problem.

**Comment by kozlovsky** [comment]
Probably it is better to treat a network with netmask `0.0.0.0` as a network with netmask `255.255.255.255`. This way, IPv8 will not take this IP address by accident.

**Comment by qstokkink** [comment]
Can reproduce on my Ubuntu 20.04 with `ifconfig enp0s3 <mylocalip> netmask 0.0.0.0`.
