### ISSUE TITLE
How to create and maintain ssh connection through IPV8

### ISSUE THREAD

**Issue by IsraelAbebe** [Tribler/py-ipv8#1067]

**Comment by qstokkink** [comment]
SSH is incompatible technology, for which IPv8 has more powerful alternatives.

IPv8 offers full anonymization per network overlay by setting `anonymize=True` in your network overlays. You are required to launch an instance of `HiddenTunnelCommunity` to provide this functionality. A short discussion is available here: https://py-ipv8.readthedocs.io/en/latest/further-reading/advanced_identity.html#enabling-anonymization
