### ISSUE TITLE
I found these papers that relate to P2P onion routing, they could help you with sybil attack resistance.

### ISSUE THREAD

**Issue by Destroyinator69420** [Tribler/py-ipv8#1077]
[tarzan_ccs02.pdf](https://github.com/Tribler/py-ipv8/files/7842972/tarzan_ccs02.pdf) source:https://www.freehaven.net/anonbib/cache/tarzan:ccs02.pdf
[morphmix_wpes2002.pdf](https://github.com/Tribler/py-ipv8/files/7842973/morphmix_wpes2002.pdf) source:https://www.freehaven.net/anonbib/cache/morphmix:wpes2002.pdf
Link to OBFS4: https://github.com/Yawning/obfs4/blob/master/doc/obfs4-spec.txt

I have linked the papers in this issue, each discusses a novel solution for preventing sybil attacks. The Tarzan protocol suggests using the scarcity of IP addresses to make it harder to launch thousands of malicious nodes, and the MorphMIx network suggests a novel algorithm to detect malicious nodes based on their behavior. I am by no means suggesting switching protocols right now, but I think that these solutions can be implemented in a later version without changing the entire protocol. These algorithms can even work better than on a client-server network since they were originally designed for P2P networks similar to py-ipv8. Since py-ipv8 3.0 is a major milestone, these solutions might be implemented then, but it is by no means urgent.

**Comment by qstokkink** [comment]
Thanks for your suggestions. You're correct, version 3.0 will be a major milestone and any changes to the anonymization will be planned after the 3.0 release (which is focused on IPv6 support). Until then anonymization improvements will not be implemented. Nevertheless, once we do start improving, it would be nice to have all of the potential improvements in one place. 

Would you mind reposting your comment in #1012? Then we can close this issue and have one dedicated issue for anonymization improvements.

**Comment by Destroyinator69420** [comment]
Sure thing, I find it interesting that Tarzan is a paper attempting to construct a p2p UDP mixnet, which is the same thing that you are trying to construct, but Tarzan does not include a trustchain as part of its protocol, which would make py-ipv8 much faster than tarzan, but Tarzan would use a novel collusion attack detector that py-ipv8 does not have, which makes that collusion attack detector a perfect feature for the 3.0 release. I will be linking the two papers in issue #1012 as you suggested.
