### ISSUE TITLE
Creating HiddenTunnelCommunity Overlays

### ISSUE THREAD

**Issue by teddyk251** [Tribler/py-ipv8#1078]
I wanted to create two nodes with the Hidden Tunnel Community and to transfer data between the two. I followed the example provided [here](https://py-ipv8.readthedocs.io/en/latest/further-reading/anonymization.html) and I keep on getting "Could not create circuit, no available exit-nodes". I tried running multiple nodes in case if the issue is related to that but I still keep on getting the same log.

**Comment by qstokkink** [comment]
The raw IPv8 network does not often see any exit node donations. Most (if not all) exit nodes operate on the Tribler network. This is because IPv8's basal anonymization protocol does not have token payout (Tribler tokens are the incentive to run exit nodes).

There are two options to get exit nodes:

 1. Run your own exit nodes to form your own private anonymized network. You can use the [IPv8 exit node script](https://github.com/Tribler/py-ipv8/blob/master/scripts/exitnode_ipv8_only_plugin.py) to launch your own exit nodes. The default configuration does not allow for anything but hidden services to be established (the exit nodes will disallow Bittorrent or HTTP to the wild Internet).
 2. Freeride on the Tribler network overlay without paying tokens. You will now be freeloading off of the exit nodes in Tribler without paying them. This will give you the worst possible service, but it will work. To do so you need to change this line:
 
    https://github.com/Tribler/py-ipv8/blob/7a94e31c1036b7d13491dc63a8e8d55ed34f0c7d/ipv8/messaging/anonymization/community.py#L95

    to `community_id = unhexlify('a3591a6bd89bbaca0974062a1287afcfbc6fd6bb')`.

**Comment by teddyk251** [comment]
I followed the second option and modified the community id then proceeded as per the documentation in building a tunnel before sending data so I run the `build_tunnels(1)` and then when running the `tunnel_data()`, I'm getting Attribute Error 'HiddenTunnelCommunity' object has no attribute 'active_data_circuits'. I used the `active_data_circuits()` method as an input for the `tunnel_data()` method as shown on the documentation.

**Comment by qstokkink** [comment]
Thanks for pointing that out. Our documentation is apparently slightly out of date. The `active_data_circuits()` method was [recently refactored](https://github.com/Tribler/py-ipv8/commit/d8265257b0cc76300cb5e9d06522c132ba58f7dd#diff-fd881f571aba60136da808ca2294c4aa082ef46795c5d46b1859fd0dc1c252b7) and you can use `find_circuits()` as a drop-in replacement.

**Comment by teddyk251** [comment]
I have now managed to send data from one node to the other using the `tunnel_data` method. I created a custom payload of type `VariablePayload`. Upon receiving the payload from the sender, the `on_packet` method is triggered on the receiving node and I get the following error.
ERROR:HiddenTunnel: Exception occurred while handling packet!
Traceback (most recent call last):
  File "/home/tewodros/protocol-engineering/nunetipv8-2/myipv8/ipv8/community.py", line 431, in on_packet
    result = handler(source_address, data)
  File "/home/tewodros/protocol-engineering/nunetipv8/venv/lib/python3.7/site-packages/ipv8/lazy_community.py", line 79, in wrapper
    signature_valid, remainder = self._verify_signature(auth, data)
  File "/home/tewodros/protocol-engineering/nunetipv8-2/myipv8/ipv8/lazy_community.py", line 241, in _verify_signature
    public_key = ec.key_from_public_bin(auth.public_key_bin)
  File "/home/tewodros/protocol-engineering/nunetipv8-2/myipv8/ipv8/keyvault/crypto.py", line 106, in key_from_public_bin
    return M2CryptoPK(keystring=string)
  File "/home/tewodros/protocol-engineering/nunetipv8-2/myipv8/ipv8/keyvault/public/m2crypto.py", line 29, in __init__
    encodebytes(keystring))
  File "/home/tewodros/protocol-engineering/nunetipv8-2/myipv8/ipv8/keyvault/public/m2crypto.py", line 45, in key_from_pem
    return serialization.load_pem_public_key(pem, backend=default_backend())
  File "/home/tewodros/protocol-engineering/nunetipv8/venv/lib/python3.7/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 30, in load_pem_public_key
    return ossl.load_pem_public_key(data)
  File "/home/tewodros/protocol-engineering/nunetipv8/venv/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 853, in load_pem_public_key
    self._handle_key_loading_error()
  File "/home/tewodros/protocol-engineering/nunetipv8/venv/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1134, in _handle_key_loading_error
    errors,
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [_OpenSSLErrorWithText(code=151584876, lib=9, reason=108, reason_text=b'error:0909006C:PEM routines:get_name:no start line')])

I generated a curve25519 key for the peer inside the Community Launcher I used.

**Comment by teddyk251** [comment]
The main reason I chose to use the HiddenTunnelCommunity is I wanted to create a secure communication between two nodes. The anonymity of the sender and the receiver is not that important to me. Is there any other way I can achieve that without using the HiddenTunnelCommunity?

**Comment by qstokkink** [comment]
By default IPv8 creates dual keys for `curve25519` for both signing and encryption. You can do something like this to encrypt message contents (I didn't add padding to the content in this example):

```python
import os
from dataclasses import dataclass

import libnacl

from ipv8.community import Community, DEFAULT_MAX_PEERS
from ipv8.lazy_community import lazy_wrapper
from ipv8.messaging.payload_dataclass import overwrite_dataclass

dataclass = overwrite_dataclass(dataclass)


@dataclass(msg_id=1)  # Important note: the message id is cleartext!
class ExampleMessage:
    content: bytes


class LinkEncryptedCommunity(Community):

    community_id = os.urandom(20)

    def __init__(self, my_peer, endpoint, network, max_peers=DEFAULT_MAX_PEERS, anonymize=False):
        super().__init__(my_peer, endpoint, network, max_peers, anonymize)

        self.add_message_handler(ExampleMessage, self.on_example_message)

    @lazy_wrapper(ExampleMessage)
    def on_example_message(self, peer, payload):
        decrypted = libnacl.public.Box(self.my_peer.key.key.sk, peer.public_key.key.pk).decrypt(payload.content)
        print(f"{peer} sent me {payload}, containing: {decrypted}")

    def send_example_message(self, peer, content):
        encrypted = libnacl.public.Box(self.my_peer.key.key.sk, peer.public_key.key.pk).encrypt(content)
        self.ez_send(peer, ExampleMessage(encrypted))

```

As an aside: in the `HiddenTunnelCommunity` we go through a DH key exchange just to get more throughput and to decouple session keys. You could also reuse that, but the code becomes a bit more complex.
