### ISSUE TITLE
LookupError: unknown encoding: idna

### ISSUE THREAD

**Issue by xoriole** [Tribler/py-ipv8#1081]
**Traceback and/or steps to reproduce**
Building Tribler with the latest PyInstaller on a Linux environment often results in a build when run raises Lookup Error on unicode hostnames. 

https://github.com/Tribler/py-ipv8/blob/33c6bdd3c643c9ca83de7fac0c3e7523e14302fd/ipv8/bootstrapping/dispersy/bootstrapper.py#L34

This issue is reported here https://github.com/pyinstaller/pyinstaller/issues/1113 and https://bugs.python.org/issue29288

**Comment by qstokkink** [comment]
IPv8 does not provide integration with PyInstaller. Providing PyInstaller related fixes should therefore conceptually be performed where PyInstaller is used, in Tribler. Am I missing any practical reason why this should be part of IPv8's codebase instead?

**Comment by xoriole** [comment]
I was able to reproduce the issue running a Linux build (from PyInstaller) but the issue is more general than running a frozen build. In my opinion, it is better to put the one-liner fix in the module where the actual triggering function is being used (here boostrapper.py) but we can also add it to Tribler if you prefer.

**Comment by qstokkink** [comment]
Thanks, now I understand why you added this to IPv8/`bootstrapper.py`. It seemed to me like this was some PyInstaller quirk. I missed that this was a general error when performing `socket.getaddrinfo` from a thread. Please add this information to the comment of #1082.

With this new insight, I believe the fix is indeed in the proper place.

**Comment by qstokkink** [comment]
@xoriole Just to confirm something I blindly assumed: did you get the `LookupError: unknown encoding: idna` by removing the try/except block around the `gethostbyname` call (line 34)? If not, there may be a hidden bug somewhere else.

**Comment by xoriole** [comment]
@qstokkink No, it is reproducible without touching anything on the existing code, more easily on frozen build.

**Comment by qstokkink** [comment]
@xoriole 😨 that is really weird. The general except should catch any and all errors on that line. Do you have a stacktrace for this error?
