### ISSUE TITLE
ipv8 search engine

### ISSUE THREAD

**Issue by Pantyhose-X** [Tribler/py-ipv8#1102]
how to run searxng search engine on ipv8 network https://github.com/searxng/searxng

**Why you need**
We do not like google, bing, yahoo to obtain user privacy, these search engines.
We believe that privacy is protected in the IPV8 network.

**Comment by qstokkink** [comment]
Thanks for the suggestion. You are absolutely correct: IPv8 has some very powerful privacy tools and they can definitely be used to for privacy-preserving search.

I had a look at SearXNG and it seems to be a search engine aggregator. In my qualified opinion, there are two ways to achieve the same functionality:

 1. Grab the information from the big evil search engines (Google, Bing, Yahoo, etc.) and share it decentrally and in a privacy-preserving way - perhaps you could use SearXNG for this.
 2. Make your own privacy-preserving decentral search without third-party search engines.

Both option (1) and option (2) are in scope for [Tribler/Tribler](https://github.com/Tribler/tribler) and (2) is even mostly implemented. To get more help modifying the existing "search community" to your needs, I would suggest moving this issue/question to [the main Tribler repository](https://github.com/Tribler/tribler/discussions).

**Comment by Pantyhose-X** [comment]
to the main Tribler repository https://github.com/Tribler/tribler/discussions/6983
