### ISSUE TITLE
py-ipv8 on android and dotnet via jython and ironpython.

### ISSUE THREAD

**Issue by Destroyinator69420** [Tribler/py-ipv8#1107]
There is a version of python 2.7 for the java runtime enviroment called jython at https://jython.org. It is free software under the Python Software Foundation License version 2, meaning it is compatible with the GPL. This would make it possible to compile jython to android, since it is written in java. A stripped down runtime could be used to intepret py-ipv8 on android. The only changes needed to py-ipv8 would be python 2.7.2 support. It would also be possible to run py-ipv8 on .net platforms via ironpython as well. Ironpython supports python 2.7.12 and python 3.4, which the latter is in public beta. By supporting python 2.7.2 and 2.7.12, it would be possible to get py-ipv8 to run on both java and dotnet, althoiugh libsodium would need to be swtiched out for bouncy castle, which supports java and C#.  py-ipv8 could be made faster by obfuscating the source for so the intrepreter has less source code to intrepret. For clarification, why does py-ipv8 use libsodium instead of openssl-1.1.1x or openssl 3.0.X?

**Comment by qstokkink** [comment]
There are currently two ways to run IPv8 for Android:

 1. A (student) port of this repo in the Kotlin language: https://github.com/Tribler/kotlin-ipv8/tree/master
 2. A custom [python-for-android (https://github.com/kivy/python-for-android)](https://github.com/kivy/python-for-android) build.

I consider both of these options superior to the options you named, which would require backward compatible support with ancient unsupported versions of Python and the use of alternative libraries.

I believe the options I gave cover your suggestion and I'll close this issue.
