### ISSUE TITLE
ModuleNotFoundError: No module named 'pyipv8'

### ISSUE THREAD

**Issue by Darken-kun** [Tribler/py-ipv8#1109]
First of all, let me clarify that I don't have any familiarity with programming, so please forgive me if that's a dumb issue that's easy to be solved. Also forgive me if this post has some english mistakes, that's not my primary language.

So I was following [this guide](https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial.html) to get started with IPv8 and I got stuck in the "run main.py" part, the cmd returns me the following:

> C:\Users\User\Documents\ipv8_tutorial\pyipv8>py main.py
> Traceback (most recent call last):
>   File "C:\Users\User\Documents\ipv8_tutorial\pyipv8\py main.py", line 3, in <module>
>     from pyipv8.ipv8.configuration import get_default_configuration
> ModuleNotFoundError: No module named 'pyipv8'

The guide says that if this step fails, it's because "I'm probably missing dependencies", but I don't know what I'm supposed to do from there.

I'm using Python 3.11.1 on Windows 7 x64 (this version of Python isn't natively compatible with Win7, but I've managed to install it through [this repository](https://github.com/adang1345/PythonWin7)). I used pip to install the dependencies from **requirements.txt**, and I also installed Libsodium 1.0.18 x64 by copying libsodium.dll to C:\Windows\system32, as specified on Readme.md.

Is there some other step I'm missing? Or maybe it's just a compatibility issue because I'm trying to run a custom version of Python 3.11.1 on Windows 7?

EDIT: I've gone through the same steps on another PC running Windows 11 and it returned me the same issue.

**Comment by qstokkink** [comment]
No worries: you're always welcome to ask a question. From your traceback it seems that your file structure is as follows:

```
ipv8_tutorial\pyipv8\ <<ipv8 files>>
ipv8_tutorial\pyipv8\main.py
```

If I got that right and this is indeed your setup, then the import `pyipv8.ipv8.configuration` is expected to fail. The fix would be to put `main.py` one folder up into `ipv8_tutorial\main.py`.

I haven't tested IPv8 on 3.11 yet and I don't know what you might run into. Please feel free to share any issues you may encounter.

**Comment by Darken-kun** [comment]
Oh I see, so that was my mistake. I thought `main.py` had to be inside the `pyipv8` folder. It's working now, thanks for the help.
