### ISSUE TITLE
Add unit test for config json serialization

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1124]
One of the key parts of IPv8's base* configuration is its ability to be serialized to JSON. That means that all keys are UTF-8 strings and all values are [JSON-compatible types](https://docs.python.org/3/library/json.html#json.JSONEncoder).

We do not have tests for JSON serialization in `TestConfiguration`. Unit test(s) for this behavior should be added.

_*Individual overlays may choose to insert raw Python objects into the configuration dict, if they extend it._

**Comment by xoriole** [comment]
An idea would be to define a JSON schema and test the config against the schema.

**Comment by qstokkink** [comment]
@xoriole thanks for the suggestion. We already have `marshmallow` as a dependency, which we can use for validation.

According to https://marshmallow.readthedocs.io/en/stable/quickstart.html#validation 

> [Schema.load()](https://marshmallow.readthedocs.io/en/stable/api_reference.html#marshmallow.Schema.load) (and its JSON-decoding counterpart, [Schema.loads()](https://marshmallow.readthedocs.io/en/stable/api_reference.html#marshmallow.Schema.loads)) raises a [ValidationError](https://marshmallow.readthedocs.io/en/stable/marshmallow.exceptions.html#marshmallow.exceptions.ValidationError) error when invalid data are passed in.
