### ISSUE TITLE
Slow execution of `EdgeWalk.take_step()` due to frequent calls to `netifaces.ifaddresses`

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/py-ipv8#1127]
In Tribler, the `EdgeWalker.take_step()` method [intermittently exhibits slow performance](https://github.com/Tribler/tribler/issues/7427), sometimes taking several seconds to execute a single call, blocking the asyncio loop. The `EdgeWalk` is instantiated with the parameters `neighborhood_size=25, edge_length=25`.

I profiled the slow `EdgeWalk.take_step()` execution and discovered that most of the execution time was consumed by calls to `netifaces.ifaddresses` and `netifaces.interfaces`. Here are the statistics derived from profiling:
```
50332 function calls in 2.015 seconds
Ordered by: internal time

ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   580    1.577    0.003    1.577    0.003 {built-in method netifaces.ifaddresses}
   145    0.380    0.003    0.380    0.003 {built-in method netifaces.interfaces}
   150    0.007    0.000    0.008    0.000 tribler\venv\lib\site-packages\libnacl\__init__.py:506(crypto_sign)
   189    0.006    0.000    0.009    0.000 py-ipv8\ipv8\peerdiscovery\network.py:219(get_verified_by_address)
   105    0.005    0.000    0.005    0.000 {method 'acquire' of '_thread.RLock' objects}
   150    0.004    0.000    0.004    0.000 {method 'sendto' of '_socket.socket' objects}
   725    0.003    0.000    1.965    0.003 py-ipv8\ipv8\messaging\interfaces\endpoint.py:171(_get_interface_addresses)
   145    0.002    0.000    0.002    0.000 {built-in method builtins.__build_class__}
  9765    0.002    0.000    0.002    0.000 py-ipv8\ipv8\peer.py:72(addresses)
   450    0.001    0.000    0.003    0.000 py-ipv8\ipv8\messaging\serialization.py:353(pack_serializable)
   580    0.001    0.000    0.003    0.000 py-ipv8\ipv8\messaging\interfaces\endpoint.py:185(__init__)
   145    0.001    0.000    0.001    0.000 {method 'getsockname' of '_socket.socket' objects}
   150    0.001    0.000    1.988    0.013 py-ipv8\ipv8\community.py:225(create_introduction_request)
   145    0.001    0.000    1.969    0.014 py-ipv8\ipv8\messaging\interfaces\endpoint.py:299(_get_lan_address)
     1    0.001    0.001    2.015    2.015 py-ipv8\ipv8\peerdiscovery\discovery.py:110(take_step)
   580    0.001    0.000    0.001    0.000 py-ipv8\ipv8\messaging\interfaces\endpoint.py:217(<listcomp>)
  9770    0.001    0.000    0.001    0.000 {method 'values' of 'dict' objects}
  1175    0.001    0.000    0.001    0.000 {built-in method _socket.inet_aton}
   145    0.001    0.000    1.971    0.014 py-ipv8\ipv8\community.py:204(my_preferred_address)
  3096    0.001    0.000    0.001    0.000 {method 'get' of 'dict' objects}
   150    0.001    0.000    0.001    0.000 Python39\lib\ctypes\__init__.py:48(create_string_buffer)
   150    0.001    0.000    0.014    0.000 py-ipv8\ipv8\lazy_community.py:233(_ez_pack)
  1160    0.001    0.000    0.001    0.000 {built-in method _struct.unpack_from}
   150    0.001    0.000    1.994    0.013 py-ipv8\ipv8\community.py:461(walk_to)
   435    0.000    0.000    0.001    0.000 py-ipv8\ipv8\messaging\serialization.py:195(pack)
  2212    0.000    0.000    0.001    0.000 {built-in method builtins.isinstance}
```

The total execution time for `EdgeWalk.take_step()` was 2.015 seconds. Of this, 1.577 seconds were spent in `netifaces.ifaddresses` and 0.380 seconds in `netifaces.interfaces`.

Even though each invocation of `netifaces.ifaddresses` or `netifaces.interfaces` was reasonably fast (0.003 seconds per call), the sheer quantity of these calls (580 calls to `netifaces.ifaddresses` and 145 to `netifaces.interfaces`) resulted in a significant accumulation of execution time.

**Proposed Mitigation:**

To enhance the performance of the `take_step` method, it should be possible to cache the results from `netifaces.ifaddresses` and `netifaces.interfaces`. The cache duration could be a few seconds, significantly boosting the speed of the `take_step` calls while maintaining network information accuracy.

I see #1123 is discussing retiring `netifaces` altogether. I would like to clarify that for this specific performance concern, the `netifaces` library is not inherently problematic. The issue arises from the frequency of its function invocations, occurring several hundred times per second. It's plausible that substituting `netifaces` with another library might not result in a significant speed enhancement, as the call speed would likely be comparable. Therefore, regardless of the library in use, it looks worthwhile to cache the results of these function calls to optimize performance.

**Comment by qstokkink** [comment]
Thanks for the stats. In order to cache these results we need changes that are extremely tightly tied to the changes made for #1123 and the WIP implementation/fix for that issue also already includes caching. To keep the discussions focused, I'll close this issue in favor of #1123.
