### ISSUE TITLE
`Network.get_peers_for_service()` can cause peers to vanish

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1131]
For unknown reason, a call to `Network.get_peers_for_service()` can (in some cases) cause a following call to `Network.get_peers_for_service()` to produce wrong results. This call _should_ only be a getter and not modify the state of the `Network` instance. However, with the right series of successive calls, its return values change.

This unit test (added to `TestNetwork`) reproduces the issue:

```python
    def test_cache_reconstruct(self):
        """
        Check if services caches are reconstructed properly.
        """
        service1 = bytes(range(20))
        service2 = bytes(range(20, 40))
        service3 = bytes(range(40, 60))
        self.network.reverse_service_cache_size = 1
        self.network.add_verified_peer(self.peers[0])
        self.network.add_verified_peer(self.peers[1])

        self.network.discover_services(self.peers[0], [service1, ])
        # We know of {<Peer 0>: ["service 1"]}

        peers_for_s3_none = [p for p in self.network.get_peers_for_service(service3)]
        # > Result for "service 3" should be an empty list.
        self.assertListEqual([], peers_for_s3_none)

        self.network.get_peers_for_service(service2)
        self.network.discover_services(self.peers[0], [service3, service2])
        # We know of {<Peer 0>: ["service 1", "service 2", "service 3"]}

        self.network.get_peers_for_service(service2)  # <--- !!!This breaks the test!!! --->>>
        self.network.discover_services(self.peers[1], [service3])
        # We know of {<Peer 0>: ["service 1", "service 2", "service 3"], <Peer 1>: ["service 3"]}

        peers_for_s3_two = [p for p in self.network.get_peers_for_service(service3)]
        # > Result for "service 3" should be [<Peer 0>, <Peer 1>].
        self.assertIn(self.peers[1], peers_for_s3_two)
        self.assertIn(self.peers[0], peers_for_s3_two)
```

By commenting out the line marked with `# <--- !!!This breaks the test!!! --->>>`, the unit test passes. To reiterate, this is only a getter and _should not change_ the outcome of the following `get_peers_for_service()` call.

EDIT: This unit test can be smaller:

```python
    def test_cache_reconstruct(self):
        """
        Check if services caches are reconstructed properly.
        """
        service1 = bytes(range(20))
        service2 = bytes(range(20, 40))
        self.network.reverse_service_cache_size = 1
        self.network.add_verified_peer(self.peers[0])
        self.network.add_verified_peer(self.peers[1])

        self.network.discover_services(self.peers[0], [service2, service1])
        self.network.get_peers_for_service(service1)  # <--- !!!This breaks the test!!! --->>>
        self.network.discover_services(self.peers[1], [service2])

        peers_for_s2_two = [p for p in self.network.get_peers_for_service(service2)]
        self.assertIn(self.peers[1], peers_for_s2_two)
        self.assertIn(self.peers[0], peers_for_s2_two)
```

**Comment by qstokkink** [comment]
The following patch seems to fix this:

```patch
diff --git a/ipv8/peerdiscovery/network.py b/ipv8/peerdiscovery/network.py
index a1e7626..2f10c4d 100644
--- a/ipv8/peerdiscovery/network.py
+++ b/ipv8/peerdiscovery/network.py
@@ -110,12 +110,13 @@ class Network(object):
             else:
                 self.services_per_peer[key_material] |= set(services)
             for service in services:
-                service_cache = self.reverse_service_lookup.get(service, [])
-                # Ensure that the peer instance in the cache is the same one as in verified_peers.
-                if peer in service_cache:
-                    service_cache.remove(peer)
-                service_cache.append(self.verified_by_public_key_bin.get(key_material, peer))
-                self.reverse_service_lookup[service] = service_cache
+                service_cache = self.reverse_service_lookup.get(service, None)
+                if service_cache is not None:
+                    # Ensure that the peer instance in the cache is the same one as in verified_peers.
+                    if peer in service_cache:
+                        service_cache.remove(peer)
+                    service_cache.append(self.verified_by_public_key_bin.get(key_material, peer))
+                    self.reverse_service_lookup[service] = service_cache

     def add_verified_peer(self, peer: Peer) -> None:
         """
```

**Comment by qstokkink** [comment]
Alright here is the breakdown of the failure per call (using the smaller unit test posted in OP):

1. `self.network.discover_services(self.peers[0], [service2, service1])` Both services get a new cache that includes `self.peers[0]`.
2. `self.network.get_peers_for_service(service1)` The getter call observes that the cache is now of size `2` (1 over the maximum cache size) and it removes the oldest cache, the cache for `service2`.
3. `self.network.discover_services(self.peers[1], [service2])` This call observes that there is no cache for `service2` and it adds a new cache that includes `self.peers[1]`. **This is wrong**, as `self.peers[0]` is also part of `service2` (even though this is no longer cached) and the cache should include both peers.

The fix posted above makes sure that no _new_ caches are added in `discover_services()`. That properly forces the cache to be rebuilt in `get_peers_for_service` if necessary.

**Comment by synctext** [comment]
To document for the future. On 29 May 2023 we nearly had a global outage of the Tribler overlay discovery network. With the 2 instances of "Packet of Death", we had another very close call in our 18 years of uptime history.
```
only getting "0.0.0.0" introduction addresses returned. Out of 13 contacted bootstrap nodes, 
only one had a WAN address to introduce for the DiscoveryCommunity
```
Our tooling obviously did not send SMS message alerts to wake up the volunteer on duty :rocket:

**Comment by qstokkink** [comment]
For this bug to disrupt an overlay, every bootstrap node needs to encounter more than 500 (which is the cache size "in the wild") different community ids in between introduction requests for that particular overlay. You need a lot of different users querying a lot of different communities for that to happen. The positive note is that we now have so many users that this bug is noticeable. Suffering from success ✌️
