### ISSUE TITLE
Don't use real socket for REST tests

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1149]
Our REST tests are roughly a factor 100 slower than our other unit tests. ~~The main reason for these slow tests is that~~ _[EDIT: apparently sockets were not to blame for these slow tests]_ our tests open and use a real socket for these tests:

https://github.com/Tribler/py-ipv8/blob/0444baa7c09b74b4495f1cadbf97de548755c661/ipv8/test/REST/rest_base.py#L118

To speed up our test suite, we should avoid opening a real socket.

---

One solution to this issue is to implement the `aiohttp.web.BaseSite` interface and use the mocked internet approach of `AutoMockEndpoint`, instead of using `aiohttp.web.TCPSite` when testing:

https://github.com/Tribler/py-ipv8/blob/ea41739927a975442c7bcdeb28078e676087c614/ipv8/REST/rest_manager.py#L105

We would also have to modify the `RESTManager` to allow the site to be altered.

**Comment by drew2a** [comment]
Could be useful: https://docs.aiohttp.org/en/stable/testing.html#faking-request-object

**Comment by qstokkink** [comment]
@drew2a thanks for the link.

I made a PR for this functionality but not using real sockets actually slows our tests down by a factor ~x1.5. It appears sockets were not to blame after all. I'll update OP.

What is causing the 100x slowdown, described in OP, is still a mystery.

**Comment by qstokkink** [comment]
Maybe I judged too fast. The ~x1.5 slowdown is only on Linux parallel.

### Total Time Parallel

Platform | With Sockets (Old) | Without Sockets (New)
--- | --- | ---
Linux | 5.55 s | 7.03 s
Mac | 11.41 s | 11.39 s
Windows | 12.79 s | 12.0 s

### Total Time Sequential

Platform | With Sockets (Old) | Without Sockets (New)
--- | --- | ---
Linux | 39.29 s | 44.46 s
Mac | 61.09 s | 63.33 s
Windows | 71.14 s | 69.42 s

**Comment by qstokkink** [comment]
Regarding own unit tests that do not perform file I/O and no socket I/O, these results suggest that the internals of `aiohttp` are "just that slow". Practically, this means that it may not be possible to go below ~40ms per REST unit test, while still using the real `aiohttp` backend.
