### ISSUE TITLE
Peerdiscovery tests are failing.

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1177]
The Jenkins job for [bootstrap server liveness](https://jenkins-ci.tribler.org/job/Test_BootstrapServers/) is failing:

```python
[Test_BootstrapServers] $ /bin/sh -xe /tmp/jenkins[...].sh
+ /usr/bin/python3 py-ipv8/stresstest/bootstrap_rtt.py
Traceback (most recent call last):
  File "py-ipv8/stresstest/bootstrap_rtt.py", line 23, in <module>
    from ipv8.util import create_event_with_signals
ImportError: cannot import name 'create_event_with_signals' from 'ipv8.util' (/home/jenkins/.local/lib/python3.8/site-packages/ipv8/util.py)
```

We are now flying blind. This should be fixed ASAP.

**EDIT: The bootstrap job is now running again. The peerdiscovery jobs are still broken.**

**Comment by qstokkink** [comment]
The same error appears for [job/performance_peer_discovery](https://jenkins-ci.tribler.org/job/ipv8/view/Network%20Health%20(periodic%20jobs)/job/performance_peer_discovery/) and [performance_peer_discovery_defaults](https://jenkins-ci.tribler.org/job/ipv8/view/Network%20Health%20(periodic%20jobs)/job/performance_peer_discovery_defaults/).

**Comment by qstokkink** [comment]
I tried wiping out the workspace but the job is not even running anymore. We may be out of disk space again.

**Comment by qstokkink** [comment]
Actually, the tests are not running on #1176. This may be an even bigger issue.

**Comment by egbertbouman** [comment]
Maybe it's using the IPv8 from PyPI which doens't have this new function?

**Comment by qstokkink** [comment]
I can confirm that [the file exists with the appropriate function in the workspace](https://jenkins-ci.tribler.org/job/ipv8/view/Network%20Health%20(periodic%20jobs)/job/performance_peer_discovery/ws/ipv8/util.py/*view*/).

At this point, I think its a Jenkins issue.

**Comment by egbertbouman** [comment]
Sure  `performance_peer_discovery/ipv8/util.py` exists, but it seems to be looking for `create_event_with_signals` in `/home/jenkins/.local/lib/python3.9/site-packages/ipv8/util.py`.

**Comment by qstokkink** [comment]
Ah, good catch. I guess someone installed IPv8 on `bbq` recently?

Regarding the badges disappearing: thanks @devos50 for cleaning up some experiment data. That part of the issue now seems solved.

**Comment by qstokkink** [comment]
Judging by the logs, between 3 and 4 PM yesterday this failure started.

**Comment by qstokkink** [comment]
Ah, it's not just `bbq`: `himba-linux-builder` has the same issue.

**Comment by egbertbouman** [comment]
If you set the Python path during the job, shouldn't everything be fine? Something like `export PYTHONPATH=$(pwd):${PYTHONPATH}`

**Comment by qstokkink** [comment]
@qstokkink that works, I'll do that for all failing jobs.

**Comment by qstokkink** [comment]
Or try, I guess.. Jenkins is not having a good day today:

![settings](https://github.com/Tribler/py-ipv8/assets/3630389/f13cee81-3b0c-48bb-a68f-b432c6b73df5)

**Comment by qstokkink** [comment]
Alright sitrep:

 - 🆗 Badges
 - 🆗 PR tests
 - 🆗 Periodic `Test_BootstrapServers`
 - 🚫 Periodic `performance_peer_discovery`: cannot apply configuration changes.
 - 🚫 Periodic `performance_peer_discovery_defaults`: cannot apply configuration changes.

At least our bear minimum critical infrastructure is now operational. I'll scale this issue down to high.

**Comment by qstokkink** [comment]
When it rains, it pours:

![github status](https://github.com/Tribler/py-ipv8/assets/3630389/d3e1b450-17ab-47cb-9c31-43c1b822fe19)

**Comment by qstokkink** [comment]
Many thanks to @kozlovsky for figuring out which plugins needed an upgrade.

We are back up and operational! Thanks to everyone who helped fix this!
