### ISSUE TITLE
use Python secure random number generation, not the default one

### ISSUE THREAD

**Issue by synctext** [Tribler/py-ipv8#130]
pycharm was complaining. in zero-knowledge lib. Use OS secure generator. Details @klikooo @wkmeijer.

**Comment by qstokkink** [comment]
I assume you are talking about the use of `randint` in [the modular additive inverse creation](https://github.com/Tribler/py-ipv8/blob/master/ipv8/attestation/wallet/primitives/attestation.py#L16).
There is no need to use secure random numbers there. Therefore I left the random number creation to the insecure PRNG of Python, which is faster.

In the actual cryptography itself we are using [full-on OpenSSL secure random number generation](https://github.com/Tribler/py-ipv8/blob/master/ipv8/attestation/wallet/primitives/cryptosystem/boneh.py).

**Comment by synctext** [comment]
Excellent. Please put a one-liner in the comments.
