### ISSUE TITLE
Add resend mechanism to Endpoint

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#149]
The new endpoint never reschedules packets, it only drops them.

This is lethal for most communities. Instead we should be able to handle short outages.

**Comment by synctext** [comment]
It is always dangerous to start building features of TCP. Historical lesson is that you often end up redoing TCP. Gossip can tolerate loss, it always worked like that for Tribler. Can we keep that loss-tolerant protocol property?

**Comment by synctext** [comment]
Oops, sorry. Guess you mean local drop. Before the UDP packets even hit the network. Smart to retry and expose the local queue buildup.
