### ISSUE TITLE
deliver_messages in test suite is unreliable when switching between reactor/thread pool

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#155]
The `deliver_messages` method, which is used to wait until all messages that are sent by IPv8 during the unit tests are delivered, is unreliable in some situations. For instance, when a chain of events is triggered by a single message and some of these events are executed on the reactor thread, `deliver_messages` might, falsely, think that there are no workers left any more, and fires. This occurs more often when considering longer tasks on the reactor thread (i.e. TrustChain block validation).

While I might get around this by executing everything on the thread pool, this is sometimes not possible. For instance, calls with the Twisted library (i.e. firing a deferred) should be done on the reactor thread.

**Comment by qstokkink** [comment]
`deliver_messages` was not made to support message flows which depend on running on the reactor thread. In fact, the entirety of IPv8 is made in such a way that a dependency on running on the reactor thread is discouraged.

If you do really need this functionality, you should not use `deliver_messages`\*.

\*It is also infeasible to create a **stable** `deliver_messages` which would support using the reactor thread.
