### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by FFY00** [Tribler/py-ipv8#204]
Is it possible to create a release? This is will help when packaging `tribler` or other dependent packages. Thanks.

**Comment by qstokkink** [comment]
Sure.

For Tribler, it would make sense to have the IPv8 `1.0` release coincide with the Tribler `7.1` release.

Is there any urgency in this request? If so, we could already make a `0.x` release now.

**Comment by FFY00** [comment]
No. I intend to move Tribler to the `[community]` repo in Arch Linux. My GPG key still needs to be signed by the master key holders which should take another 2/3 weeks. Does that work for you?

**Comment by qstokkink** [comment]
Hmm.. I'm not sure if `7.1` will be out before that. Could you make another post ITT when you're all set and signed? Then we'll make a release for you.

**Comment by FFY00** [comment]
I don't know if we really need to do that. I might be allowed to temporarily checkout to a specific commit if needed. I will run this by other TU and let you know.

**Comment by FFY00** [comment]
Can a release be added now or were you waiting for `7.1.0` instead of `7.1.0-beta`?

**Comment by qstokkink** [comment]
We were waiting for the `7.1.0` release to tag IPv8 as `1.0`. Has your situation changed?

**Comment by FFY00** [comment]
I am pulling the latest commit atm. Should work fine.

**Comment by qstokkink** [comment]
I created the release for `v1.0`: https://github.com/Tribler/py-ipv8/releases/tag/v1.0
From now on we'll maintain a version.
