### ISSUE TITLE
CryptographyDeprecationWarning: signer and verifier have been deprecated

### ISSUE THREAD

**Issue by xoriole** [Tribler/py-ipv8#205]
Version 2.0 of cryptography was release in July 2017 and signer and verifier are now deprecated in favor of sign and verify. We should consider upgrading already the code.

**Comment by qstokkink** [comment]
This is already half-way done:

https://github.com/Tribler/py-ipv8/blob/5e7a72c4cad08cb7312fe34c57063527159de299/ipv8/keyvault/private/m2crypto.py#L71-L76

**Comment by qstokkink** [comment]
@xoriole actually, are you sure this is an IPv8 issue and not a Dispersy issue?

**Comment by qstokkink** [comment]
As I believe this is not an issue for IPv8, but Dispersy. I will assume this to be a Tribler issue, fixed when Dispersy is gone.

**Comment by xoriole** [comment]
I'm not sure. This was a warning only.

**Comment by qstokkink** [comment]
@xoriole Dispersy is the only location I can still find the old use of sign and verify.
