### ISSUE TITLE
Improve performance of block validation when the database grows

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#250]
Right now, our tunnel helpers have high amounts of I/O (observed with `iotop`) because of the validation procedure of TrustChain blocks. When walking through the network, a peer requests new blocks from introduced peers and validates them. With a large database (1,000,000+ blocks) this process generates a significant amount of I/O and delays since queries take longer to complete. I think it is important to address this issue soon since it might affect the download speeds of Tribler users.

First, we should get more insight in how much of the time is spent on individuals calls to the database. We can use the Yappi profiler to get insights into the CPU usage and maybe some other tool to get insight into the I/O performance.

One way to address this problem is to cache blocks in the memory and only do a database query when we actually add content to the database. For my market experiments, I created a highly optimized (yet memory-hungry) database for this. I'm not sure how much memory this would exactly require though. Another mechanism we could consider is to queue blocks for validation and reject blocks from others when the queue is full. This prevents the possibility for other users to spam the network with (invalid) blocks. However, this is probably future engineering.

**Comment by devos50** [comment]
Yappi report:

<img width="683" alt="yappi_ipv8_report" src="https://user-images.githubusercontent.com/1707075/45252166-9dbe8880-b352-11e8-93b5-1266a17564e9.png">

There are some interesting observations in the report. Database queries are (only?) responsible for around 5% of all CPU ticks. We see that a significant amount of ticks is dedicated to the `get_walkable_addresses` method. I will create a separate issue for this. Also, converting M2Crypto public keys to binary takes a heavy amount of time.

Based on this, I'm not sure how much we would actually win if we optimize the database and store everything in memory. For dedicated experiments where we have to push the limits (like I did with the market experiment), a memory database would help but I would rather add this to Gumby then.

**Comment by qstokkink** [comment]
While fixing #407 I noticed we [check the chain length during every introduction request/response](https://github.com/Tribler/py-ipv8/blob/master/ipv8/attestation/trustchain/community.py#L648), this is a mad amount of database io.

**Comment by devos50** [comment]
When running the TrustChain crawler, it seems to occasionally block for a few seconds. This could be related to a large number of disk I/O operations?

**Comment by the-man-with-a-golden-mind** [comment]
Can you use RocksDB or LevelDB as a main database? It can reduce the size of the content(snappy alg), it is way more faster then SQLite, PostgreSQL. You can build some logic above the basic laver (RocksDB has beed used as a one of possible Cassandra backends). Most of the blockchain projects are using RocksDB as their main database for a transactions.

**Comment by devos50** [comment]
> Can you use RocksDB or LevelDB as a main database?

Yes, I'm currently working on a persistence layer that is compatible with key/value storage like the ones you mentioned. Not sure when it will be finished but I will test its performance with [our TrustChain explorer](https://explorer.tribler.org).

**Comment by qstokkink** [comment]
We have a block memory cache now, the issue -as originally posted- is fixed. We should reevaluate our current performance (and open a new issue with up-to-date results if necessary).
