### ISSUE TITLE
get_walkable_addresses uses a considerable amount of CPU cycles

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#252]
To address issue #78, I enabled Yappi for the TrustChain crawler and monitored CPU usage over a period of a few hours. See the following report:

<img width="683" alt="yappi_ipv8_report" src="https://user-images.githubusercontent.com/1707075/45252213-3a812600-b353-11e8-88c4-dedd22f65eec.png">

The `get_walkable_addresses` method takes a significant amount of processing power (38.5%!). A breakdown shows that almost all this time is spent in the `<dictcomp>` method, which in turn has the following performance:

<img width="689" alt="yappi_breakdown" src="https://user-images.githubusercontent.com/1707075/45252234-77e5b380-b353-11e8-851f-9d142ccd0b17.png">

This makes walking through the network expensive in terms of CPU usage. @qstokkink is there any easy way to make this more efficient?

**Comment by qstokkink** [comment]
Most of the hurt seems to actually be in the `<dictcomp>` in `network.py`:

https://github.com/Tribler/py-ipv8/blob/d89d7bb42e4647cf34f14966b9c3ae0bf1632f8a/ipv8/peerdiscovery/network.py#L151-L152

We could optimize this.

**Comment by devos50** [comment]
I managed to reproduce this one in Gumby, with an overly aggressive walker (with walking interval 0.05 sec or 20x/sec). In this experiment with 500 nodes, 70.01% is spent on `get_walkable_addresses` method. Also, 23.78% of the time is spent in `b64encode`.

This should give us a baseline for optimising the `network.py` file.

**Comment by qstokkink** [comment]
I think we can just strip NetworkX out of `network.py`, nobody is using the actual graph anyway. Also, that saves a dependency.
