### ISSUE TITLE
Taskmanager fails to register task with duplicate name

### ISSUE THREAD

**Issue by ichorid** [Tribler/py-ipv8#253]
https://github.com/Tribler/py-ipv8/blob/d89d7bb42e4647cf34f14966b9c3ae0bf1632f8a/ipv8/taskmanager.py#L35-L45

When one tries to add a new task with a name that's already registered, Taskmanager will:
1. Cancel this new task (L43)
2. **Unregister the original task** (L44)

This results in unmanaged delayed calls dangling in the reactor. For example, calling `remove_exit_socket` twice for the same exit socket triggers this behavior.

**Comment by ichorid** [comment]
Gonna fix it in https://github.com/Tribler/tribler/pull/3842, but we have to discuss what kind of behavior is desirable when trying to add a task with duplicate name.

**Comment by qstokkink** [comment]
Please put it in a separate PR. The expected behavior is to error out.
