### ISSUE TITLE
DHT Looping call for peer churn

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#273]
The DHT community has a `ping_all` looping call for peer management. This mechanism should use the appropriate `DiscoveryStrategy` class instead. Perhaps the other `LoopingCall`s can also be moved to this mechanism, but I have not investigated this.

In part this also resolves the testability issue pointed out by @ichorid, that we should be able to advance time manually as much as possible for staging (instead of relying on background tasks managed by Twisted). The `DiscoveryStrategy` class exposes `take_step` which allows us to control when peers are pinged or removed.

This also removes a lot of clutter from the community.

**Comment by ichorid** [comment]
That would be very nice, indeed!

**Comment by DanGraur** [comment]
I've implemented this, and forwarded a PR: #352.
