### ISSUE TITLE
TrustChain (and other communities) should deal with UDP message drops

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#314]
During one my of test runs, I noticed that it can happen that payouts blocks are not signed by the other party. I pinpointed the error to the fact that the crawl request message did not arrive at all (while the logs seem to indicate that it was sent). This resulted in a half block that was not signed. Only when the other party crawls the chain of the transaction originator, it will come across this block and signs it, if the block is valid.

TrustChain should be able to deal with UDP messages that are dropped for any reason and retry the crawl.

**Comment by ichorid** [comment]
I argue that this should be implemented in the TrustChain community itself, and not in the endpoint. We don't want to repeat the whole TCP stack...

**Comment by qstokkink** [comment]
I agree with @ichorid this should be handled in the `on_timeout()` of `RequestCache`s.
