### ISSUE TITLE
the made-in-Holland SSI toolkit

### ISSUE THREAD

**Issue by synctext** [Tribler/py-ipv8#328]
Principle: deployment driven, continuous delivery. The Code Demo is the progress report.

Architectural and roadmap principles:
- running-code 
- incrementalism
- relentless focus: growing strength of attestations
- minimalism: only define the open ID wallet
  - openness: freedom to create a new ID
  - fire-walled: different IDs are shielded from each other by default
  - no restrictions: open container to freely build upon
- be very afraid of semantics and ontology

Sprint period: 1 week or 1 quarter?

Divide the work into parallel stream (however, never break compatibility) with different objectives:
- privacy first-prototyping
- security first-prototyping
- usability first-prototyping
- deployment first-prototyping

Open Question: how to integrate and progress together?
federation (one aspect, API alignment?) versus competition (overlap, full-stack)

Platform and programming language choice:
- Like Linux: first patch wins?
- How to avoid platform contest?
- How to avoid favorite Haskell vs. Kotlin?

Avoid in first iterations:
- legal compliance with current legal framework
- stringent security weakness review
- maintenance, support, and operations

**Comment by franken01** [comment]
Ps, ikv nick szabo, kijk eens naar het haviltex arrest (naar de geest van of de regel van het contract)

**Comment by synctext** [comment]
Divide the work into parallel stream (however, never break compatibility). Reason: currently no solution combines biometric authentication, maturity, and proven-in-deployment. 

We seek to avoid fragmenting our efforts, ensure that lessons in any stream can be applied in others and parallel streams are architectural compatible. We need to define some commonality. This should be minimalistic, no undue strain on parallel innovations. Perhaps we reduce the constrains the most by only defining the minimal at the lower level in the architecture: the attestation. For instance: 

```
+--------+---------------------------------+----------------------+----------------+
| Number |           Description           |         Type         |  Size (bytes)  |
+--------+---------------------------------+----------------------+----------------+
|    0   |   Public Key in Binary Format   | Unsigned Short Array |        n       |
+--------+---------------------------------+----------------------+----------------+
|    1   | Global Time (Lamport Timestamp) |  Unsigned Long Long  |        8       |
+--------+---------------------------------+----------------------+----------------+
|    2   |       Attestation Metadata      |   Char Array (Raw)   |     33 + m     |
+--------+---------------------------------+----------------------+----------------+
|        |             *Total:*            |                      |   64 + n + m   |
+--------+---------------------------------+----------------------+----------------+
```

With multi-signature attestation looking, for instance, like this:
![attestation](https://user-images.githubusercontent.com/325224/47079760-7e930080-d206-11e8-8c0e-e3bc54303274.png)

**Comment by synctext** [comment]
- ***joint fact finding***
  - re-use the wealth of prior efforts, legal knowledge and existing technology
  - parties agree to do early prototyping
  - evidence building
- ***evidence-based selection***
  - select both flagship use-cases (government,commercial) and platform
  - iterative process; from long-list, short-list to final remainder or empty-list
  - meets requirements such as: legally valid SSI, ability for biometric authentication, truly open, privacy, etc.
- ***result-driven realisation***
  - build a new legal framework for identity
  - build concrete flagship use-cases
  - public-private partnership based on utility model
- ***breaking-even support***
  - minimize long-term cost for authentication, support and maintenance
  - internationalization and maximize usability in physical world

**Comment by synctext** [comment]
Today it was decided that we will not try to find the killer app of an SSI or drive deployment. We will deploy and facilitate an open innovation ecosystem. This will include a fully functional open source SSI app on the Google Play store. Current draft name "regie op gegevens". Planned functionality in Toolbox:
- [ ] read passport NFC chip
- [ ] sign a message with passport NFC chip
- [ ] identity wallet management
  - [ ] login with DigiD to mijn.overheid
  - [ ] download attestations using https://tlswitness.org/ technology
  - [ ] certificate of legal entity representation
  - [ ] attestation of taxable income and other attributes
  - [ ] attestation of Github username
- [ ] messages, signatures, legal entities and contracts
  - [ ] messaging and message box on trustchain
  - [ ] legal entity attestation, signed by chamber of commerce
  - [ ] signed and authenticated messaging contact point for a legal entity
  - [ ] legally valid electronic signature; signed and validated by chamber of commerce ("_handtekening-register_")
  - [ ] legally binding machine readable electronic contract signed by multiple legal entities
- [ ] general supportive utilities
  - [ ] electronic notary services with legal validity and authentication
  - [ ] browse trustchain (select testnet, mainnet, and create new)
  - [ ] visualize the IPv8 overlay
  - [ ] open source biometrics for fingerprint creation using smartphone camera

Screenshots of current operational prototypes:
![trustchain_android__signature_requests_and_mailbox](https://user-images.githubusercontent.com/325224/35418338-f8bca6cc-0231-11e8-966a-ad82eee456d5.gif)
![image](https://user-images.githubusercontent.com/9843576/34727645-deca1574-f557-11e7-89f9-df9124e79179.png)
![image](https://user-images.githubusercontent.com/325224/50916975-b348d980-143c-11e9-8a39-2f273b78de48.png)
![screenshot_20180123-115803](https://user-images.githubusercontent.com/9843576/35272244-df07f924-0034-11e8-927f-b605a7dc2def.jpg)
![image](https://user-images.githubusercontent.com/325224/50917101-09b61800-143d-11e9-86e1-08e1038b209c.png)
![image](https://user-images.githubusercontent.com/325224/50917701-81387700-143e-11e9-98d7-49f4dbbb9f82.png)
![image](https://user-images.githubusercontent.com/8111083/35012000-750946da-fb08-11e7-9340-8f3125792bc6.png)
![image](https://user-images.githubusercontent.com/8111083/35012903-c44addd2-fb0b-11e7-8fef-10e2d024751c.png)
![image](https://user-images.githubusercontent.com/8111083/35011705-6a815d52-fb07-11e7-8e87-975a71044e86.png)
![image](https://user-images.githubusercontent.com/325224/50917941-29e6d680-143f-11e9-93c7-612d2a11317e.png)
Photo donated to the Public Domain. No copyrights claimed.
![overlay_android_manual_test__jan2018](https://user-images.githubusercontent.com/325224/35271864-b435387a-0033-11e8-8f35-c9b10b6f34cd.jpg)

**Comment by synctext** [comment]
Key use-case for SSI is verifiable claims with legal certainty. _Non verifiable information about verifiable reality_ is the default for birth certificates, bank notes, diplomas, [etc](https://medium.com/coinmonks/social-network-for-any-token-960afd36d280).

The legal [framework is eIDAS within the EU](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32015R1502&from=EN%3E). eIDAS usage at level "high" requires possible usage of "photo or biometric identification evidence recognised by the Member State". This regulation has a soft-inclusion link to an ISO standard: "_ the definitions and concepts in ISO/IEC 29115 should be taken into the utmost account when establishing the specifications and procedures set out in this implementing act_". [International Standard ISO/IEC DIS 29115 ](https://www.oasis-open.org/committees/download.php/44751/285-17Attach1.pdf), free download copy instead of paying for EU rules. This eIDAS from 2015 [also builds upon the 2014 rules](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014R0910&from=EN). The rules are broad and also cover "Binding between the electronic identification means of natural and legal persons".

ISO/IEC 29115 includes: **Level of assurance 4 (LoA4)**, "very high". This ISO standard states that LoA4 **must** make "use of tamper-resistant hardware devices for the storage of all secret or private cryptographic keys". There is prior work on open source, open hardware tamper-resilient storage of credential. At Delft University we devised the first "patent-free PUF" device: Tribler/tribler#3064.

Other work includes "destroy-upon-opening", the costly ORWL device. Mostly positive review: "[ORWL PC: The most secure home computer ever](https://www.pcworld.com/article/3118264/security/orwl-pc-the-most-secure-home-computer-ever.html)". ![image](https://user-images.githubusercontent.com/325224/52405957-d82c7d00-2acc-11e9-87b5-e09d260c31f2.png). Plus a [critical review](https://blog.invisiblethings.org/2016/09/03/thoughts-about-orwl.html).

Systemic flaw in level "high" eIDAS is the lack of audit-ability, transparency and tampering detection. We propose level "maximum": with additional end-to-end security integrity guarantees. Level "maximum" provides a tamper-proof access and audit trail for all data access actions, system monitoring actions, system maintenance actions, and all other operations. At no point in time will data be exposed to unknown operations, unknown access by unknown software or unknown hardware. Every action and behavior of the system **must** be able to independently reproduced, verified and audited.

**Comment by synctext** [comment]
Security of biometrics. Confirmed that fake face has been used for identity theft and multi-million Euro fraud. [ Fake French minister in a silicone mask who stole millions](
https://www.bbc.co.uk/news/world-europe-48510027)

**Comment by andredekok** [comment]
Ja dit is echt big business

Op do 20 jun. 2019 1:30 p.m. schreef Johan Pouwelse <
notifications@github.com>:

**Comment by synctext** [comment]
@davila9210 of Rabobank has [done an interesting writeup on a self-sovereign identity demo](https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/topics-and-advance-readings/universal-ledger-agent.md).
![image](https://user-images.githubusercontent.com/325224/61783443-18c44c80-ae08-11e9-8864-f7aaf0e385d5.png)
![image](https://user-images.githubusercontent.com/325224/61783532-414c4680-ae08-11e9-8313-b78f0cd98962.png)

**Comment by qstokkink** [comment]
With the merge of #541, we will have the ability to import BRP data from the Nijmegen IRMA server.

![anim_loginirma](https://user-images.githubusercontent.com/3630389/62194981-44e94b80-b37b-11e9-82f2-f79d6342f180.gif)

We use:
 1. The usual DigiD login mechanism of Nijmegen (through https://services.nijmegen.nl/irma/issue).
 2. Read the QR code from the HTTPS session automatically and close the browser window (for mobile use, the user would have to manually scan the QR code).
 3. Communicate with the IRMA foundation keyshare server for a temporary account (this is necessary - otherwise the Nijmegen server will not sign).
 4. Get the "idemix" signature over our data from the Nijmegen server.
 5. Form the proof structure around our own data, deviating slightly from the original IRMA protocol. Our change consists of *not storing the actual attribute values* on the device. Instead, we only prove that (1) we have seen the attribute values and (2) know the secret value used for issuance.

The output of this enrollment wrapper can then be interpreted by our TrustChain identity and used for future proving of the exposed BRP data. Concretely you have the option of including any of the following 4 TrustChain attributes:

 - *bsn*
 - *ageLimits* (older than 12, 16, 18, 21, 65)
 - personalData (initials, firstnames, prefix, familyname, surname, fullname, dateofbirth, gender, nationality)
 - *address* (street, houseNumber, zipcode, municipality, city)

**Comment by andredekok** [comment]
Mooie prestatie

Op wo 31 jul. 2019 9:30 a.m. schreef Quinten Stokkink <
notifications@github.com>:

**Comment by synctext** [comment]
Related work: [Trust over IP](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0289-toip-stack) with solid group [discussions](https://github.com/hyperledger/aries-rfcs/issues/294).

**Comment by synctext** [comment]
With the field trail of SSI: https://github.com/Tribler/tribler/issues/4461 we've made another solid step forward. Closing this general issue.
