### ISSUE TITLE
Use six.moves as much as possible

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#382]
Right now we have some Python 3 compatibility definitions in [`util.py`](https://github.com/Tribler/py-ipv8/blob/master/ipv8/util.py) which are already available in [`six.moves`](https://pythonhosted.org/six/#module-six.moves). We should keep code duplication (with available libraries) to a minimum, so we should switch to the `six.moves` library instead.

**Comment by cclauss** [comment]
Also wherever practical, please follow the Python porting best practice [__use feature detection instead of version detection__](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection) as it will placate the linters (PyLint, flake8, etc.).
