### ISSUE TITLE
Clarify terms in TrustChain documentation

### ISSUE THREAD

**Issue by synctext** [Tribler/py-ipv8#401]
Explain in a few lines what the ```half block``` concept is. Plus community and "additional info" of the transaction API call for block_creation. What is a linked block? Not easy to read.
Method signed block: public_key parameter expects the remote peer (not your key); confusing.

https://py-ipv8.readthedocs.io/en/latest/further-reading/trustchain/

**Comment by qstokkink** [comment]
Judging from the git blame we should assign this to @devos50 .

**Comment by devos50** [comment]
...

**Comment by qstokkink** [comment]
Perhaps we have a paper around somewhere with a good introductory explanation?

**Comment by devos50** [comment]
I'll finish this one tomorrow.
