### ISSUE TITLE
Explore: Linux kernel and hardware support for IPv8

### ISSUE THREAD

**Issue by synctext** [Tribler/py-ipv8#43]
Possible research directions: towards a fast clean-slate network stack or support multi-path routing out of the box. problem of protocol [ossification](https://lwn.net/Articles/667059/). Prior work: [how to receive a million packets per second](https://blog.cloudflare.com/how-to-receive-a-million-packets/). This is opposed to moving the IPv8 research to the database side of the stack. There is also the DHT, connect to anybody connect() primitive with network mobility. 

[Linux kernel support for UDP tunneling from 2015](http://people.netfilter.org/pablo/netdev0.1/papers/UDP-Encapsulation-in-Linux.pdf). Open Hardware support, like [White Rabbit Network Interface Card](https://www.ohwr.org/projects/wr-nic/wiki/wiki). Scientific article [a multi-port 10GbE PCIe NIC featuring UDP offload and GPUDirect capabilities](http://iopscience.iop.org/article/10.1088/1742-6596/664/9/092002/pdf). Other work [Realtime Ethernet Device Driver](http://www.opentech.at/assets/papers/udp.pdf).

**Comment by qstokkink** [comment]
Out of scope for this century.
