### ISSUE TITLE
Switch completely to python3

### ISSUE THREAD

**Issue by NULLx76** [Tribler/py-ipv8#463]
To quote [python.org](https://wiki.python.org/moin/Python2orPython3): "_Python 2.x is legacy, Python 3.x is the present and future of the language_". 

I think python2 support is a really weird choice for such an innovative project as this.

I don't think a rewrite to 3 would be _that_ hard as you state it is already python3 compatible. There also could be made use of the `2to3` utility for the initial conversion and if wanted of the `3to2` utility to generate the python2 version when needed (can't really see why though). 

Some benefits of using python3 instead of 2 include but are not limited to:
* Faster execution speed
* Better Unicode support
* non-local variable declarations
* Function annotations
* Exception chaining
* etc.

The current usage of `__future__` imports is also very hack-y in my opinion and will be solved by actually updating to python3.

**Comment by synctext** [comment]
Yes, we're very much working on this.
Note that this 'innovative project' started in April 2005. Our larger Tribler codebase needs lot of care&attention.

**Comment by ichorid** [comment]
@NULLx76 , if you want to help with the issue, please, look around the tracker for related issues. Also, take a look at the [Tribler developers guidlines](https://tribler.readthedocs.io/en/devel/contributing.html).

**Comment by devos50** [comment]
@NULLx76 thanks for your feedback. While theoretically, this would be possible, IPv8 is used as a dependency of Tribler, which is not Python 3 compatible yet. As @synctext notes, this is an ongoing effort which takes a lot of time. Until then, we decided to support both Python 2 and 3.

**Comment by NULLx76** [comment]
Ah okay that makes sense. I will see what I can do to help port both Tribler and IPv8 to python3

**Comment by jonay2000** [comment]
Yeah, @NULLx76 and me will probably try to convert some code over. The project seems extremely cool!

**Comment by devos50** [comment]
Cool! Shall I add both of you to our slack channel if you want to discuss this a bit more?

**Comment by jonay2000** [comment]
sure! im already in a mattermost channel with some of you (Sander, Johan, and it seems many more)

**Comment by qstokkink** [comment]
That's a lot of misinformed opinions and assumptions in the O.P., I'll focus on the most important issues.

> I think python2 support is a really weird choice for such an innovative project as this.

It's not a choice, it's a 14 year legacy. As mentioned, our main upstream usage is Tribler, which is only Python 2 compatible at the moment. It would defeat the purpose of our existence to break with our main upstream project.

> I don't think a rewrite to 3 would be that hard as you state it is already python3 compatible.

Indeed, it wouldn't be that hard. We use `six` everywhere to make sure all of the code is compatible with both the Python 2 and Python 3 versions of all of our dependencies. Only `database.py` and `util.py` have non-six compatibility code, the rest is a simple find and replace on `six` usage. At this point fully switching would be done in half an hour.

> There also could be made use of the 2to3 utility for the initial conversion and if wanted of the 3to2 utility to generate the python2 version when needed (can't really see why though).

It is not as easy as running a simple tool to convert some scripts. Considering our dependencies, I had to painstakingly go through our code line by line -over a period of several weeks- to ensure consistent behavior over Python versions.

> The current usage of \_\_future\_\_ imports is also very hack-y in my opinion and will be solved by actually updating to python3.

Just like usage of the `six` module, this is part of the best practices in porting code to Python 3 (see also [python.org](https://docs.python.org/3/howto/pyporting.html)). 

Yes, at some point we can fully switch to Python 3, but that time is not now. At the very least we have to wait until https://github.com/Tribler/tribler/milestone/31 is resolved. But even then, we have other upstream projects, like student work, depending on our Python 2 compatibility.

As it makes no sense to put any effort into fully switching to Python 3 for IPv8 at this moment in time, I will put this issue on hold.

**Comment by qstokkink** [comment]
The Python 3 switch now exists in the form of the `asyncio` branch. The full switch proceedings are documented in #616, superseding this issue.
