### ISSUE TITLE
Use `python2 -m pip` instead of `pip` in documentation

### ISSUE THREAD

**Issue by TimSpeelman** [Tribler/py-ipv8#485]
When running `pip install ..`, the packages are installed for the default Python version, which may very well be Python 3. This lead me into some problems of the `cannot find module X` kind, which I resolved by using `python2 -m pip ..` after figuring out the problem.

Although it is more of a general pip thingy, given that we use python 2, we may want to be explicit with the pip installs as well. This saves people some trouble. If agreed, I'll make a PR.

**Comment by qstokkink** [comment]
We don't just use Python 2. You can also use Python 3. You should use `pip2` or `pip3` accordingly.

**Comment by qstokkink** [comment]
By using `pip` the system selects the most appropriate Python distribution for you.

**Comment by TimSpeelman** [comment]
Allright, would you say this is something we could clarify in the docs or let the user figure that out? We do explicitly mention `python2` in the README, attestation and overlay tutorial. 

Also, `pip2` does not work out of the box for me on Windows, but that could be my problem.

**Comment by qstokkink** [comment]
The average user will probably only have one Python version installed. Nevertheless clarity in the documentation is always good.

The mentions of Python 2 in the documentation are out of date, that should be updated. We now support both Python 2 and Python 3.

**Comment by devos50** [comment]
> The average user will probably only have one Python version installed.

When installing a clean Ubuntu version, you usually have Python 2 and 3 installed (since there are some dependencies that use either Python 2 or Python 3). However, usually `python2` is symlinked to `/usr/bin/python`.

**Comment by qstokkink** [comment]
Closed by #486
