### ISSUE TITLE
Crawl SQL logic does not always fetch the right linked block

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#521]
When working on the market, I found out that the SQL logic of the crawler is not always returning the right blocks. This SQL statement is currently as follows:

```
SELECT * FROM
(
    SELECT type, tx, public_key, sequence_number, link_public_key, link_sequence_number, previous_hash, signature, block_timestamp, insert_time
    FROM blocks
    WHERE sequence_number >= ?
        AND sequence_number <= ?
        AND public_key = ?
    LIMIT ?
)
UNION SELECT * FROM 
(
    SELECT type, tx, public_key, sequence_number, link_public_key, link_sequence_number, previous_hash, signature, block_timestamp, insert_time
    FROM blocks
    WHERE link_sequence_number >= ?
        AND link_sequence_number <= ?
        AND link_sequence_number != 0
        AND link_public_key = ?
    LIMIT ?
)
```

Here, it is assumed that the linked blocks are within the same range as the `start_seq_num` and `end_seq_num` as the query. This is not always true, e.g., when `start_seq_num = 1`, `end_seq_num = 2` and there is a linked block with sequence number 3. Specifically, it does not always return the right linked blocks.

I'm not entirely sure how to fix this within a single SQL statement. One solution would be to first fetch the non-linked blocks and then fetch linked blocks one by one in another SQL statement. However, this would be quite expensive in terms of CPU usage since a new SQL query has to be initiated for each non-linked block returned by the database.

**Comment by qstokkink** [comment]
*I formatted your post's SQL statement to span multiple lines*

I don't see the problem. It seems like the `UNION SELECT` is basing itself on `link_sequence_number`, which should correspond to the blocks on the requested range for the requested public key.

Do you have an minimal example of what is broken?

**Comment by devos50** [comment]
The minimal example will probably involve three peers, I will make one 👍

**Comment by devos50** [comment]
Reproduced the bug with the following minimal test:

```
@inlineCallbacks
    def test_crawl_linked_block(self):
        """
        Test whether we get correct linked blocks when crawling the chain of a specific peer
        """
        his_pubkey = self.nodes[1].network.verified_peers[0].public_key.key_to_bin()
        yield self.nodes[1].overlay.sign_block(self.nodes[1].network.verified_peers[0], public_key=his_pubkey,
                                               block_type=b'test', transaction={})

        # Now, a third peer crawl the chain of peer 0. We should both get the linked block and the originating block.
        self.add_node_to_experiment(self.create_node())
        yield self.nodes[2].overlay.send_crawl_request(self.nodes[0].my_peer,
                                                       self.nodes[0].my_peer.public_key.key_to_bin(), 1, 1)

        # Peer 2 should have 2 blocks now
        self.assertEqual(self.nodes[2].overlay.persistence.get_number_of_known_blocks(), 2)
```

The bug is that the crawl SQL logic assumes that there are only "originating" half blocks in the chain of the crawled peer. This is obviously not always true. I think I can extend the SQL statement to also account for this case.

**Comment by qstokkink** [comment]
> The bug is that the crawl SQL logic assumes that there are only "originating" half blocks in the chain of the crawled peer. 

I see now, thanks for the example.
