### ISSUE TITLE
Requesting multiple attestations from same peer

### ISSUE THREAD

**Issue by TimSpeelman** [Tribler/py-ipv8#534]
My peer (at port 8124) requested an attestation on attribute Y1 from peer `mid:X`:
`POST http://localhost:8124/attestation?type=request&mid=Xattribute_name=Y1&metadata=Z` which returned `200 OK`

Peer `mid:X` received the attestation, as it showed up in:
`GET http://localhost:14410/attestation?type=outstanding` but I left the request unanswered.

My first peer then made another request, for attribute Y2:
`POST http://localhost:8124/attestation?type=request&mid=Xattribute_name=Y2&metadata=Z` which returned a `500` with a very unclear error message:

```
error	{…}
message	This number is already in use '340785898481379423394501292456235217245106609921'
code	RuntimeError
handled	false
trace	[…]
0	File "C:\python\lib\site-packages\twisted\web\server.py", line 199, in process self.render(resrc)
1	File "C:\python\lib\site-packages\twisted\web\server.py", line 259, in render body = resrc.render(self)
2	File "C:\python\lib\site-packages\twisted\web\resource.py", line 250, in render return m(request)
3	File "C:\python\lib\site-packages\ipv8\REST\attestation_endpoint.py", line 242, in render_POST self.attestation_overlay.request_attestation(peer, attribute_name, key, metadata)
4	File "C:\python\lib\site-packages\ipv8\attestation\wallet\community.py", line 138, in request_attestation self.request_cache.add(ReceiveAttestationRequestCache(self, peer.mid, secret_key, attribute_name, id_format))
5	File "C:\python\lib\site-packages\ipv8\attestation\wallet\caches.py", line 74, in __init__ mid, id_format)
6	File "C:\python\lib\site-packages\ipv8\attestation\wallet\caches.py", line 36, in __init__ super(PeerCache, self).__init__(request_cache, prefix, number)
7	File "C:\python\lib\site-packages\ipv8\requestcache.py", line 23, in __init__ raise RuntimeError("This number is already in use '%s'" % number) 
```

My questions:
1. (Why) Is it not allowed to ask a peer for multiple attestations, without the peer answering first?
2. (Why) Is it not allowed to ask the peer multiple times for the same attribute?
3. Is this behaviour expected?
4. Could we improve upon this error message?

**Comment by qstokkink** [comment]
Documentation of our physical Q/A session:

1. You are not allowed to spam others.
2. See (1).
3. Yes, though you _should_ be allowed to ask for different attributes at the same time (**needs investigation**).
4. We should indeed probably make the error message more beautiful.

**Comment by qstokkink** [comment]
(3) is caused by our data transfer protocol. We open channels and filter packets based on either *a predetermined hash* of the data which will be sent to us or *the sender of the data*. This gives the sending party a limited timeframe to send the big blob of data (and avoids the receiving peer potentially being forced into opening many connections). Whereas we can handle as many data streams with predetermined hashes as we want, data streams with unknown length are limited to 1 per public key.

So, for now, we are limited to one concurrent attribute request per peer. We would have to rework the protocol to support concurrent requests.
