### ISSUE TITLE
Inappropriate responses from attestation_endpoint

### ISSUE THREAD

**Issue by TimSpeelman** [Tribler/py-ipv8#536]
I have already fixed one issue in PR #535.

However, I feel that more attestation_endpoint responses are inappropriate. I would like to verify this before making the changes:
1. `GET|POST /attestation?type=blah` returns `{ success: True }` (#535 fixes this)
2. `GET /attestation?type=attributes&mid=x` returns attributes if a peer `x` is known, but otherwise it returns `{ success: True }`
3. `POST /attestation?type=request&mid=x ..` and `POST /attestation?type=verify&mid=x ..` return `{ success: True }` when the peer `x` is not known!

I suggest solving each:
1. Return `{ error: "incorrect type argument" }`
2. Return `[]`
3. Return `{ error: "peer unknown" }`

If this is ok, I will fix it.

**Comment by devos50** [comment]
I think the attestation API (and more generally, the IPv8 "RESTful" API) is not up to the standards. This includes inconsistent use of HTTP response codes, non-informative request responses and a lack of easy to understand unit tests. So I think any contribution that aims to make the API more consistent and meaningful is already a step in the right direction.

IIRC, the Idemia Android app is using the attestation API so your changes might break their app. I think your proposed changes are ok but @qstokkink should give the final verdict 👍

**Comment by qstokkink** [comment]
Sure 👍 

We used to just return a JSON null value (`b""`) on failure, but since a38fad9eec7b414e8827f745a1bbe74c5a326262 we have half-assed return codes. Now it's not only ugly, but also inconsistent 😃
