### ISSUE TITLE
Change "data" to a dict or class instance. 

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [Tribler/py-ipv8#553]
https://github.com/Tribler/py-ipv8/blob/1b08fb2c8f05330bcf578af72f75c62a3c64af4c/ipv8/attestation/trustchain/block.py#L30

Changing data to a dictionary or a Data class instance would reduce the complexity of the code below (in a TrustChain constructor). It would also make it a little bit more clear and easier to read.

**Comment by qstokkink** [comment]
Thanks for the suggestion, I'll make a `Data` class.
