### ISSUE TITLE
Using fetching all can reduce the performance and increase the amount of memory usage.

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [Tribler/py-ipv8#554]
https://github.com/Tribler/py-ipv8/blob/1b08fb2c8f05330bcf578af72f75c62a3c64af4c/ipv8/attestation/trustchain/blockcache.py#L38

There is no reason of using fetch_all. Fetching all rows will make it slower and less efficient. 
If you would return Cursor to the DB then you can iterate it like a generator (btw. there is iteration below...so once again no needs for fetching all the data). 
If there would be plenty of rows then Python could have also some problems with memory allocation (which can bind memory leaks in the future).

**Comment by qstokkink** [comment]
I fully agree. However, there is a catch that necessitates this construction: we have multi-threaded access of the database class.

SQLite 3 cannot handle different threads acccessing it at the same time. Though we can use Locks to simply make sure no two threads access the database at the same time, we cannot leave a cursor 'open' between accesses. This causes all database access to -necessarily- be atomic. Which is slow.

The proper fix for this, would be to use a database manager which can handle asynchronous access. Or some other, fundamental, rewrite of our database code. Therefore, I believe #250 suffiently covers this issue and I will close this one to keep the discussion in the other issue.
