### ISSUE TITLE
Add BPASE state of the art

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#56]
Some recent advancements in key fragmentation ([pyUmbral](https://github.com/nucypher/pyUmbral)) and proofing (Bulletproofs) can be integrated into IPv8's ID framework for large performance gain.

**Comment by synctext** [comment]
Related work similar to IPv8 overlay (not identity part) :
- IPFS/ Libp2p  https://github.com/libp2p/specs/blob/master/3-requirements.md
- Pulsar Apache pub-sub https://github.com/apache/incubator-pulsar
- FreeLAN https://raw.githubusercontent.com/freelan-developers/freelan/master/fscp.txt
- ToX https://toktok.ltd/spec.html#goals
- UDP punching https://github.com/vi/udpnat
- Telehash http://telehash.org/
- OpenOverlayRouter https://github.com/OpenOverlayRouter/oor

- Maidsafe Crust https://github.com/maidsafe/crust/blob/master/README.md

![crusty](https://github.com/maidsafe/crust/blob/master/img/crust-diagram_1024.png?raw=true)

Our design philosophy is to enable trustworthy any-to-any communication. We want a very light-weight approach. For instance, `libp2p` is a much more heavy and broader approach. See their feature set:
  - Enable the use of various:
    - transports: TCP, UDP, SCTP, UDT, uTP, QUIC, SSH, etc.
    - authenticated transports: TLS, DTLS, CurveCP, SSH
  - Make efficient use of sockets (connection reuse)
  - Enable communications between peers to be multiplexed over one socket (avoiding handshake overhead)
  - Enable multiprotocols and respective versions to be used between peers, using a negotiation process
  - Be backwards compatible
  - Work in current systems
  - Use the full capabilities of current network technologies
  - Have NAT traversal
  - Enable connections to be relayed
  - Enable encrypted channels
  - Make efficient use of underlying transports (e.g. native stream muxing, native auth, etc.)

**Comment by qstokkink** [comment]
I've taken the time to investigate in-depth and read through the code; I concluded that the technology is interesting, but not interesting and/or mature enough to include in its current form.

As I see no immediate gain, I will close this issue. We can open other issues as new solutions surface.
