### ISSUE TITLE
Custom ask about _DEFAULT_ ADDRESSES

### ISSUE THREAD

**Issue by cattaneomn** [Tribler/py-ipv8#572]
I would like to know how to replace the _DEFAULT_ ADDRESSES ips with one of my own ipv8 nodes to try to do a parallel network. 

https://github.com/Tribler/py-ipv8/blob/master/ipv8/community.py

**Comment by qstokkink** [comment]
You will need to have your own tracker node(s). You can launch one as follows (from the IPv8 main directory):

```bash
export PYTHONPATH=.
twistd -n tracker --listen_port=13131
```

Substitute `13131` with whatever port you want to listen on.

After this, make sure you remove all entries you don't want from `_DEFAULT_ADDRESSES ` and `_DNS_ADDRESSES` and add your own node and port combination to either (a) `_DEFAULT_ADDRESSES ` for an ipv4 and port tuple or (b) `_DNS_ADDRESSES` for a DNS name and port tuple.

**Comment by cattaneomn** [comment]
Thanks for responding so fast, I'm going to try it.

**Comment by cattaneomn** [comment]
It worked perfect thanks, I will investigate more about how a tracker works in the library.
