### ISSUE TITLE
Trying to make a simple p2p network without using Dispersy trackers

### ISSUE THREAD

**Issue by cattaneomn** [Tribler/py-ipv8#573]
I'm trying to create a simple p2p network using the library. To do that i guess that the first step it would be to have peers that know each others.

Im trying to do a p2p overlay like the tutorial (https://github.com/Tribler/py-ipv8/blob/master/doc/basics/overlay_tutorial.md), but also i m trying to ovewrite the trackers addresses in _DEFAULT_ADDRESSES (https://github.com/Tribler/py-ipv8/blob/master/ipv8/community.py) with my own trackers. 

For that i would like to know if its make sense to write a main.py with the overlay tutorial behaviour and also with the tracker service one (https://github.com/Tribler/py-ipv8/blob/master/twisted/plugins/tracker_plugin.py), and put in the _DEFAULT_ADDRESSES the ip and ports that i set on the trackers before run them.

**Comment by qstokkink** [comment]
I'm not entirely sure what you mean by "make sense", so let me answer both of my interpretations:

_Regarding it making sense in the implementation_
If you bring the tutorial code together with your trackers correctly with your custom code, you should also be able to use the tutorial code. Yes.

_Regarding it making sense as a concept_
Also yes: this is a good place to start off your first dabbling with IPv8 overlays.

**Comment by cattaneomn** [comment]
Taking as a reference the tutorial of overlay (https://github.com/Tribler/py-ipv8/blob/master/doc/basics/overlay_tutorial.md#printing-the-known-peers).
I edit the main.py leaving it like these:

    #New lines of code START
    service_maker = TrackerServiceMaker()
    options = Options()
    options["listen_port"] = int(sys.argv[1])
    service_maker.makeService(options)
    #New lines of code END

    IPv8(configuration, extra_communities={'MyCommunity': MyCommunity})

reactor.run()

Then i edit also the community.py(https://github.com/Tribler/py-ipv8/blob/master/ipv8/community.py), changing the _DEFAULT_ADDRESSES to these:

```
_DEFAULT_ADDRESSES = [
    ("127.0.0.1", 13130),
    ("127.0.0.1", 13131
]
```

I run the following comands in two separated terminals:
python main.py 13130
python main.py 13131

- I dont know why these two peer cant know each other, printing "I know:', []" always empty.

But if i run the main.py without the extra the two peers show that know these new one, but still dont between each other.

------------
Note:
I rewrote the MyComunity class with a fixed key:
```
class MyCommunity(Community):
    #master_key = ECCrypto().generate_key(u"medium")
    master_key = "3081a7301006072a8648ce3d020106052b8104002703819200040578e79f08d3270c5af04ace5b572ecf46eef54502c1" \
                 "4f3dc86f4cd29e86f05dad976b08da07b8d97d73fc8243459e09b6b208a2c8cbf6fdc7b78ae2668606388f39ef0fa715cf2" \
                 "104ad21f1846dd8f93bb25f2ce785cced2c9231466a302e5f9e0e70f72a3a912f2dae7a9a38a5e7d00eb7aef23eb42398c38" \
                 "59ffadb28ca28a1522addcaa9be4eec13095f48f7cf35".decode("HEX")
    master_peer = Peer(master_key)    
    time = 0

    def started(self):        
        def print_peers():
            print("T=%d" %self.time)
            print("SELF ",self)
            print("I am:", self.my_peer, "\nI know:", [str(p) for p in self.get_peers()])
            self.time = self.time + 1
        # We register a Twisted task with this overlay.
        # This makes sure that the task ends when this overlay is unloaded.
        # We call the 'print_peers' function every 5.0 seconds, starting now.
        self.register_task("print_peers", LoopingCall(print_peers)).start(5.0, True)
```

**Comment by qstokkink** [comment]
IPv8 assumes the trackers are not on the same subnet as the peers connecting to it, I'm assuming that's what's going on here. If that is the case, adding the following to your `MyCommunity` class should fix it:

```python
def introduction_response_callback(self, peer, dist, payload):
    self.walk_to(payload.lan_introduction_address)
```

**Comment by cattaneomn** [comment]
Thanks, i will try it.
Thanks I'll try.
Another question that arose, What would be the disadvantage in a p2p network that each node can be a tracker?

**Comment by qstokkink** [comment]
Hmm.. it might not be finding your trackers then. Could you print the `payload` in the `introduction_response_callback` (keep in mind it might not be receiving any)?

> Another question that arose, What would be the disadvantage in a p2p network that each node can be a tracker?

In theory that would be great, the network becomes truly distributed and virtually impossible to take down. In practice it might lead to some nasty clustering or network partitioning effects if there are too many bootstrap servers.

**Comment by cattaneomn** [comment]
I tried the same code in other environments (windows and linux) and it worked exactly as i expected.
Every peer has the IPv8 Service and the Tracker Service on.
I dont know yet why it dont work on my mac environment.
Thanks for helping me.

**Comment by qstokkink** [comment]
Cool 👍, have fun experimenting.

I don't own a Mac, so if you ever figure out what is/was wrong, please let me know.
