### ISSUE TITLE
Where are the format_list?

### ISSUE THREAD

**Issue by cattaneomn** [Tribler/py-ipv8#580]
The strings on format_list inside the Payloads, are from python or from the ipv8 library? Cause i dont find the description on the code.

example:
`format_list = ['4SH', '4SH', '4SH', '4SH', '4SH',  'bits', 'H', 'raw']`

**Comment by qstokkink** [comment]
You can find the true list here:

https://github.com/Tribler/py-ipv8/blob/ff69ec33b2db1c46e0f4b6b679ca6324d5890d90/ipv8/messaging/serialization.py#L186-L216

Mostly they resemble the native `struct` formats:

https://docs.python.org/3.9/library/struct.html#format-characters

**Comment by cattaneomn** [comment]
Do you use that to serialize data between nodes?
Why you didnt decided to use protobuff? (https://developers.google.com/protocol-buffers/)

**Comment by qstokkink** [comment]
We have a long history (14 years and counting) and needed to be backwards compatible. It wasn't so much as a consideration, as it was a necessity.

**Comment by cattaneomn** [comment]
so you dont use protobuff? or its a TODO for the future?
I think i read something about it on Tribler, but i might be wrong

**Comment by qstokkink** [comment]
Right now nothing uses protobuf.

We have switched away of the `struct` formats being necessary though. Any overlay programmer could hook protobuf structures into the `Serializer` class for their custom overlay.

**Comment by cattaneomn** [comment]
that's very useful, thanks for your answer, i will look for that
