### ISSUE TITLE
Doubt about discovering new nodes and introduction response

### ISSUE THREAD

**Issue by cattaneomn** [Tribler/py-ipv8#581]
In create_introduction_response of Community class, it sends the overlay introduction response to the new node that make a request.
In this way the nodes of the network are known one by one in each cycle of request and response,  sending 1 node of the overlay (the one that responds) by response.
Is there a reason why a list of nodes that the responding node knows is not sent?

**Comment by qstokkink** [comment]
The answer is two-fold:

 1. We use the introdcution request/responses for NAT traversal. However, this NAT puncturing has a timeout (which depends on the intermediate hardware). Puncturing a lot of NAT layers and then having all/a lot of this hole punching time out is very inefficient.
 2. Regarding abstract security: if you have a way to determine -with 100% certainty- someone's neighborhood, you could DOS attack their neighbors and attack the overlay logic.

**Comment by cattaneomn** [comment]
So that way of discovering the network one by one is cause it adds a security layer against a DOS attack to the overlay.
In the case that every node has full control over the firewall(not need NAT traversal)(not Tribler case), and in the introduction_response is sended the list of known peers of the overlay, Could it be an improve to the fast of discovering the network by the new peers? or you think it got more disadvantages that advantages?

**Comment by qstokkink** [comment]
Even with NAT, I agree that sending all of your known peers over would greatly decrease the time it would take you to discover the entire network.

If speed is all you care about, you can improve the discovery speed even more by only introducing others to peers they do not know yet (you can use an efficient set-membership data structure for this - like Bloom filters).

Also, I realized I forgot two factors in my previous answer:

 3. It's easier to reason about.
 4. There is a maximum UDP packet size, so you cannot send the full list of peers when you reach a certain number of peers.

**Comment by cattaneomn** [comment]
You are right i forgot consider the maximum UDP packet size too.
These reasons are the cause of setting a limit of the max number of peers to add in the on_introduction_request?

**Comment by qstokkink** [comment]
Yes, I think that's about all of the considerations.

**Comment by cattaneomn** [comment]
Thanks for everything, i will keep learning :)
