### ISSUE TITLE
New peer into the network 

### ISSUE THREAD

**Issue by cattaneomn** [Tribler/py-ipv8#582]
I made a diagram step by step (simplified) of the discovering process of new peers.
Do you think is it accurate in a high level?
![Walkthrough](https://user-images.githubusercontent.com/7108801/66138301-c5733500-e5d4-11e9-9bb6-6b5924df3d52.png)

**Comment by qstokkink** [comment]
That's a pretty cool visualization and seems to be accurate.

If you want more information on NAT traversal and why we do what we do regarding the introduction requests, there is an (older) paper here: [Dispersy Bundle Synchronization](https://pdfs.semanticscholar.org/94e6/26b7ff25b07d23fd345aad254abbdd0a574b.pdf)

**Comment by cattaneomn** [comment]
Thanks, i will read it

**Comment by cattaneomn** [comment]
That paper its just what i was looking for to understand Tribler's p2p infrastructure from the basics, thanks you very much.

**Comment by qstokkink** [comment]
You're welcome and thanks, I might include that in some documentation somewhere.

**Comment by qstokkink** [comment]
Inspired by your questions I have [started to expand IPv8's documentation a bit more aggressively](https://py-ipv8.readthedocs.io/en/latest/).

Would you want to make a PR for your image into our documentation (so you get proper GitHub accreditation)?
