### ISSUE TITLE
Tracker sending puncture_request with wrong prefix

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#596]
The tracker plugin rewrites packets with the requested packet prefix:

https://github.com/Tribler/py-ipv8/blob/4aceb300069cde738c00b332e1495f347947a67e/twisted/plugins/tracker_plugin.py#L92

**However**, `create_introduction_response` also sends a `puncture_request` message over with a non-overwritten prefix. This causes the fact that only the `DiscoveryCommunity` will only perform puncturing. We need to support standalone (no `DiscoveryCommunity` loaded) communities as well.

**Comment by devos50** [comment]
That would be nice indeed 👍

**Comment by qstokkink** [comment]
We will have to restart the trackers after this change.
