### ISSUE TITLE
rst docs relative links not working on readthedocs

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#603]
Our new `.rst` based documentation<sup>1</sup> uses relative links and works perfectly fine on GitHub. However, the Read the Docs page<sup>2</sup> is incredibly broken.

Frankly, I don't know what Read the Docs wants from me and I could use some help on this one.

<sup>1</sup> https://github.com/Tribler/py-ipv8/blob/master/doc/index.rst
<sup>2</sup> https://py-ipv8.readthedocs.io/en/latest/

**Comment by xoriole** [comment]
For the links to work in read-the-docs, you likely need to replace the links with `.rst` to `.html`

**Comment by qstokkink** [comment]
Does that trigger some sort of automatic detection?

Neither https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial.rst or https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial.html seems to exist.

**Comment by qstokkink** [comment]
I tried my best, but I can not see a way to get GitHub working with the Sphinx RST format. New plan: support _only_ Read the Docs and make that our primary source of human-readable documentation. GitHub will only serve as the source files required for the documentation.

We'll commit to the whole [`makefile` and `conf.py` structure](https://matplotlib.org/sampledoc/getting_started.html) in the `doc` folder.

**Comment by synctext** [comment]
Their links work:)
https://github.com/readthedocs/readthedocs.org

**Comment by devos50** [comment]
If I recall correctly, I had some major issues with (relative) links in the readthedocs for the Tribler repository (I'm not sure whether they are working at this point).

@qstokkink you are using absolute links in the `index.rst` file? Readthedocs will not properly pick these up as being separate pages included in the documentation and thus will not compile them. You should use relative links instead. Please have a look [at the same file in the Tribler repository](https://raw.githubusercontent.com/Tribler/tribler/devel/doc/index.rst). Also, I think the compilation output should show whether it is currently compiling a page or not. You can also check if the page is being compiled by checking whether the corresponding HTML file in the `build` (?) directory exists.

Also, did you create a separate account for this? We could migrate everything to the same account that already hosts the documentation of Tribler?

@synctext the links in their `README.rst` file points to the HTML page, which I think is an ok solution. It is more user-friendly to be redirected to the readthedocs pages, and we should indeed one of them make our main point of documentation, not both.

**Comment by qstokkink** [comment]
All my links are relative, but @synctext is correct, the readthedocs repo magically has both `GitHub` AND `Read the Docs` links working, see the `Reachability` link on these two pages:

https://github.com/readthedocs/readthedocs.org/blob/master/docs/abandoned-projects.rst#abandoned-projects

https://docs.readthedocs.io/en/latest/abandoned-projects.html#abandoned-projects

I'll plow through their `Makefile` to see how they have achieved this level of black magic.

**Comment by qstokkink** [comment]
Oh no never mind, those are only links on the same page. The inter-doc links are also broken on GitHub for Read the Docs: https://github.com/readthedocs/readthedocs.org/blob/master/docs/custom_domains.rst

**Comment by qstokkink** [comment]
Back to the orginal plan: we drop support for viewing the docs on GitHub.

**Comment by qstokkink** [comment]
It actually works! https://py-ipv8.readthedocs.io/en/latest/

**Comment by synctext** [comment]
Working for 1 hour on a PR that enhances the index.

**Comment by qstokkink** [comment]
Currently in the process of migrating over @DanGraur's documentation: #605
