### ISSUE TITLE
Add method to get overlay instance by class name

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#625]
We have several use cases (most notably the REST API) in which we want to get an overlay of a certain class from an `IPv8` instance. Right now, programmers must loop through the `.overlays` list and find the appropriate overlay instance for a certain class "manually".

The problem here is that we can have multiple overlays of the same class running. So we should expose two methods in the `IPv8` class:

 - `get_overlay(overlay_class)`: get an overlay instance of a certain class or None, error out if multiple overlays of the requested class are running.
 - `get_overlays(overlay_class)` : get all overlay instances of a certain class (may be an empty list).

**Comment by Solomon1732** [comment]
One enhancement I can think for `get_overlays(overlay_class)` is to instead make it a generator expression. This way if the number of overlays is large it will not cost significant overhead. Generator expressions are supported in py3 and py2, so the function can be backwards compatible.
