### ISSUE TITLE
Bare excepts may lead to unexpected behavior

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/py-ipv8#650]
#### Platform ####
All
#### Expected behavior ####
Catch specific exceptions. Or at most catch `except Exception:`.
#### Actual behavior ####
Bare excepts, whose catching may lead to unexpected behavior (such as catching `RuntimeError` or `SystemExit`).

The locations of the exceptions is provided in a list of links in the paste bin link below
https://gist.github.com/Solomon1732/73e4637aa057e99ae7c860bd9fc4dc88

**Comment by Solomon1732** [comment]
I don't mind opening a PR. However I have no idea which exception to put where. As easy as it is to write `Exception` and be done with it, I'd like to specify the exceptions in such a PR.

**Comment by qstokkink** [comment]
`RuntimeError` is a subclass of `Exception` (see https://docs.python.org/3/library/exceptions.html#exception-hierarchy) so I think all of these can be already rewritten to use `Exception`.

Secondly, I also had a manual look at if we can/should change beyond catching general `Exception` errors. Here's my evaluation:

| Verdict | Location | Reason |
|---------|---------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8_service.py#L95 | Backwards compatible key loading |
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8_service.py#L153 | Never, ever, crash the entire main loop on overlay programmer error (which happens frequently). |
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/community.py#L327 | Never, ever, crash the entire main loop on overlay programmer error (which happens frequently). |
| Modify | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/attestation/trustchain/block.py#L332 | The error is abstracted over in words. However, without the source traceback this can be annoying to debug. This error should be logged (DEBUG). |
| Remove | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/attestation/trustchain/community.py#L291 | Message handling is already in a general try .. except block, why is this even here? |
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/attestation/wallet/primitives/boneh.py#L38 | Too scared of introducing errors in the cryptography. |
| Modify | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/dht/provider.py#L49 | This error should be logged (INFO). |
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/keyvault/crypto.py#L84 | This is correct use as specified by the used library (though I admit it is not pretty). |
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/keyvault/crypto.py#L92 | This is correct use as specified by the used library (though I admit it is not pretty). |
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/keyvault/crypto.py#L133 | This is correct use as specified by the used library (though I admit it is not pretty). |
| Modify | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/anonymization/caches.py#L73 | This error should be logged (INFO). |
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/anonymization/community.py#L692 | Never, ever, crash the entire main loop on overlay programmer error (which happens frequently). |
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/anonymization/community.py#L958 | Never, ever, crash the entire main loop on data sent by third parties. |
| Review | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/anonymization/hidden_services.py#L183 | This seems sufficiently low level that we could infer the exact exception and catch that. |
| Review | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/anonymization/payload.py#L25 | This seems sufficiently low level that we could infer the exact exception and catch that. |
| Review | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/anonymization/tunnel.py#L77 | This seems sufficiently low level that we could infer the exact exception and catch that. |
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/anonymization/tunnel.py#L176 | Never, ever, crash the entire main loop on data sent by third parties. |
| Review | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/REST/dht_endpoint.py#L391 | This seems sufficiently low level that we could infer the exact exception and catch that. |
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/REST/isolation_endpoint.py#L66 | Required for proper formatting of the error for the REST interface. |
| Review | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/REST/noblock_dht_endpoint.py#L60 | This seems sufficiently low level that we could infer the exact exception and catch that. |
| Modify | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/test/attestation/trustchain/test_community.py#L599 | This is a test, we should be able to discern which exception occurs exactly. |
| Keep | https://github.com/Tribler/py-ipv8/blob/asyncio/scripts/tracker_plugin.py#L67 | Never, ever, crash the entire main loop on overlay programmer error (which happens frequently). Especially not here. |
| Modify | https://github.com/Tribler/py-ipv8/blob/asyncio/stresstest/bootstrap_rtt.py#L95 | This seems sufficiently low level that we could infer the exact exception and catch that. |
| Modify | https://github.com/Tribler/py-ipv8/blob/asyncio/stresstest/endpoint_stresstest.py#L191 | This seems sufficiently low level that we could infer the exact exception and catch that. |

**Comment by Solomon1732** [comment]
These are the review and modify instances. Please review.
| Location | Raises | Notes |
| --- | --- | --- |
| https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/anonymization/payload.py#L25 | `OSError` | https://docs.python.org/3/library/socket.html#socket.inet_aton |
| https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/anonymization/tunnel.py#L77 | `TypeError` | Both index accessing and `len` checking raise the `TypeError` |
| https://github.com/Tribler/py-ipv8/blob/asyncio/stresstest/bootstrap_rtt.py#L95 | Auditing event | [`getsocketbyname`](https://docs.python.org/3/library/socket.html#socket.gethostbyname) [`auditing event`](https://docs.python.org/3/library/sys.html#sys.audit). Please review further. From auditing event: "This function will raise the first exception raised by any hook. In general, these errors should not be handled and should terminate the process as quickly as possible." |
| https://docs.python.org/3/library/os.html#os.makedirs | `FileExistsError` | https://docs.python.org/3/library/os.html#os.makedirs. "If _exist_ok_ is `False` (the default), an `FileExistsError` is raised if the target directory already exists." Parameter can replace exception, or exception can logged. |
| https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/attestation/trustchain/block.py#L332 | None. See notes. | Uses the [`pack`](https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/attestation/trustchain/block.py#L193) method. Doesn't seem to raise errors. Kindly confirm/deny. |
| https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/attestation/trustchain/block.py#L193 | `PackError` | https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/serialization.py#L245 |
| https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/anonymization/hidden_services.py#L183| `IndexError` | [`Swarm.lookup`](https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/messaging/anonymization/tunnel.py#L444) uses [`time.time()`](https://docs.python.org/3/library/time.html#time.time) which doesn't raise errors and [`random.choice()`](https://docs.python.org/3/library/random.html#random.choice) which raises `IndexError` |
| https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/REST/dht_endpoint.py#L391 | Maybe `RuntimeError`. See notes. | Seems like it might raise `RuntimeError`, but I'm not sure. This is the method it uses https://github.com/Tribler/py-ipv8/blob/b09aba741678ef5915ed8d0a013bc985f5fe2543/ipv8/dht/community.py#L226 |
| https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/REST/noblock_dht_endpoint.py#L60 | `RuntimeError` | [`connect_peers`](https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/dht/discovery.py#L92) raises `DHTError`. [`find_nodes`](https://github.com/Tribler/py-ipv8/blob/b09aba741678ef5915ed8d0a013bc985f5fe2543/ipv8/dht/community.py#L419). [`_find`](https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/dht/community.py#L334). raises `DHTError`. |
| https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/test/attestation/trustchain/test_community.py#L599 | None. See notes. | Uses the [`process_half_block`](https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/attestation/trustchain/community.py#L362) method. Doesn't seem to raise errors. Kindly confirm/deny. |

**Comment by qstokkink** [comment]
Reviewed your review of my review:

- All socket auditing events seem to be subclasses of `OSError`: https://docs.python.org/3.8/library/socket.html#exceptions .
- `os.makedirs` will generally throw `OSError`, not just `FileExistsError`.
- `pack` will raise `PackError`: https://github.com/Tribler/py-ipv8/blob/4315d6b2b6e2f2c44c10d8e788a3d54dccadb6de/ipv8/messaging/serialization.py#L263 .
- `dht_endpoint.py` will also throw `PackError`s.
- `noblock_dht_endpoint.py`: Why `RuntimeErorr` instead of `DHTError`?
- `test_community.py` seems fine.

I wish Python had support for explicit `typing` definitions for exceptions..

**Comment by Solomon1732** [comment]
> `dht_endpoint.py` will also throw `PackErrors.`

Oh, ok. Good to know. I looked at an olded version of the function by accident 😅 
> `noblock_dht_endpoint.py`: Why `RuntimeErorr` instead of `DHTError`?

It indeed raises `DHTError`. It's a leftover of me accidentally looking at an older version of the function. I forgot to change it. In the latest version it indeed raises `DHTError`.

> I wish Python had support for explicit `typing` definitions for exceptions..

I know, right 😑 
With this a PR can go on its way, I guess?

**Comment by qstokkink** [comment]
> With this a PR can go on its way, I guess?

Yes, I believe so.

**Comment by Solomon1732** [comment]
Small update: [`process_half_block`](https://github.com/Tribler/py-ipv8/blob/asyncio/ipv8/attestation/trustchain/community.py#L362) raises a `RuntimeError`. PR will reflect it.

**Comment by devos50** [comment]
Note that call to `self.should_sign` can potentially raise many more errors, since this is a method intended to be implemented by developers. Specifically, developers can add custom validation logic for specific types of TrustChain blocks. Therefore, I suggest leaving that a generic try/catch.

In fact, the reason for various occurrences of try/except constructions in the code is to prevent the applications that are using IPv8 from crashing. In particular, Tribler crashes when even a single, unhandled error is observed.

**Comment by Solomon1732** [comment]
Right. I guess this is why @qstokkink said it's to keep. I understood it to mean change the bare to `except Exception`, but if it is not the case the PR will reflect it 😄

**Comment by Solomon1732** [comment]
Closed with #655
