### ISSUE TITLE
Inefficient list comparison in get_peers_for_service when the number of peers in a community grows

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#656]
I noticed that the Noodle crawler is using ~90% CPU constantly, even though there are not many peers in the Noodle community. When doing some profiling on the (Noodle) code, which is based on the latest commit on the `master` branch, I found a performance bottleneck. [Here](https://github.com/Tribler/py-ipv8/blob/master/ipv8/peerdiscovery/network.py#L134) we check if the `peer` is in `self.verified_peers`, which in turns invokes the `__eq__` method of the `Peer` class. This requires a call to `key_to_bin()`, which is an expensive call. Note that if the number of (verified) peers in the community grows, it becomes slower quite fast. In fact, 68.3% of the CPU usage of my crawler is spent in the `M2CryptoPK.key_to_bin` method, even with ~50 peers in the `DiscoveryCommunity`. I think this might also affect Tribler performance.

Related issue: https://github.com/Tribler/py-ipv8/issues/586.

Maybe we could save the binary public key in the `Peer` objects and use that during the comparison?

**Comment by devos50** [comment]
Pre-computing the binary public key brings back the CPU usage to 5% :octocat: . @qstokkink Is this the desired solution?

**Comment by qstokkink** [comment]
Use the `mid` instead, it is precomputed.

**Comment by devos50** [comment]
Sure, let me make a PR for that 👍

**Comment by qstokkink** [comment]
Also, the linked code already uses a cache for lookups.

**Comment by qstokkink** [comment]
Actually, `verified_peers` should probably be a `set`. `__hash__` already uses the `mid`.

**Comment by devos50** [comment]
Well, I read that linked code as: if there is a cache, construct a `list` with `Peer` objects. This actually performs the expensive list comparison.

Let me try to change `verified_peers` to a set 👍

**Comment by qstokkink** [comment]
Good point, even though the `service_cache` is quite small, the `in` operator for the `verified_peers` is still a list (therefore not hashed and the `in` operator is then not efficient). Making it a `set` should solve the performance issue.

**Comment by devos50** [comment]
Hmm it seems, that `verified_peers` is used quite a lot. @qstokkink could you make this change?

**Comment by qstokkink** [comment]
It'll also probably break Tribler.

**Comment by devos50** [comment]
Hmm true, should we change the comparison function to use the `mid` then instead?

**Comment by qstokkink** [comment]
Better to do it right the first time around, I'll give it a go.

**Comment by devos50** [comment]
Ok, good luck with that 👍
