### ISSUE TITLE
next paper brainstorm

### ISSUE THREAD

**Issue by synctext** [Tribler/py-ipv8#662]
public brainstorm on thesis chapter.

- IPv8: Trust over IP.
Article focus on generic method and plugins, operational bootstrap and experimental deployment. trustchain. Trust in Tribler:
-spam channels
-spam in returned search results
-spam on decentral market
-votes on channels
-polute popularity sample
-malware in IPv8 plugin
-fraud on decentral market
-spy on our ethical darknet

@grimdas pinky sweared he would help...

- A happy marriage of Tor, QUIC congestion and video streaming.
Copy cell structure of Tor. get to 100mbit per second somehow, compare to Tor. Story: privacy that scales. 

- DAPPv8: distributed Apps you can rely on.
create an execution layer on IPv8. sandboxing, community API evolution, crowd sourcing, voting, Mitchell work++,pub/sub, etc.

- Trustchain: trust that scales
show that this could replace tech companies and underpin the global economy. Huge datasets from web2.0 on ratings and reviews. data on identity theft and Facebook troll account closures. support multiple economic sectors with 1 fabric.

- Trustworthy gossip. try to publish yet another gossip paper using PeerSim.

**Comment by synctext** [comment]
battle of the decentral stacks: IPFS, DAT, and Tribler
https://news.ycombinator.com/item?id=22094376

**Comment by qstokkink** [comment]
This issue has been superseded by in-office discussion.
