### ISSUE TITLE
WAN destination address used as LAN walker address

### ISSUE THREAD

**Issue by MattSkala** [Tribler/py-ipv8#686]
Let's assume A creates an introduction request and sends it to B. B sends an introduction response to A and a puncture request to C. The puncture request is supposed to contain LAN and WAN addresses of A that C should contact. 

While WAN walker address is set to `peer.address` of peer A, the LAN walker address is set to the WAN address of B that it received in `IntroductionRequestPayload.destinationAddress` field. Is there any reason for that? I would expect `IntroductionRequestPayload.sourceLanAddress` to be used as LAN walker instead. And maybe `IntroductionRequestPayload.sourceWanAddress` to be used as WAN walker instead of `peer.address`, which is not guaranteed to be a WAN address if they are on the same LAN.

Related code:
https://github.com/Tribler/py-ipv8/blob/d9f52435f3b81975b2b1e47793fc0742a9fc733b/ipv8/community.py#L273

**Comment by qstokkink** [comment]
This should be compensated for here:

https://github.com/Tribler/py-ipv8/blob/a949ccb33e38a40b3632b5520ab8c6e149b457bc/ipv8/community.py#L304-L311

Do note that these are all estimates of the WAN and LAN interface addresses. Depending on the insane NAT configuration these estimates can be very wrong. This is the magical construction created to deal with all of the edge cases, created back in the Dispersy days.

I am reluctant to change this, as we do not have a test bed for different NAT configurations. Rashly changing this could fundamentally break the connectivity.

**Comment by MattSkala** [comment]
If I understand the code correctly, then this condition in `on_puncture_request` causes that if A has the same WAN as C, then C sends a puncture message back to B, which is the peer who sent the puncture request in the first place. I don't see a case where this could be useful, but I'll just assume there is some edge case where this is needed.

**Comment by qstokkink** [comment]
Ah I see now, yes you are correct. The shipped `lan_walker_address` comes from the `destination_address`. This is indeed wrong.

This has been working all the time, as peers on the same subnet don't require additional puncturing. Nothing gained, nothing lost.

**Comment by qstokkink** [comment]
The required changes for this will be included with the fix of #615: to streamline dicussions I will close this issue.
