### ISSUE TITLE
The value of socket.SO_RCVBUF is likely to be application-specific

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#692]
Right now, [we set the UDP buffer size to the maximum size of a UDP datagram](https://github.com/Tribler/py-ipv8/blob/7ba563d6a9e2f98dae016b286fa26c468548f3d2/ipv8/messaging/interfaces/udp/endpoint.py#L68). Even though this might look like a solid solution to minimize UDP packet loss, I experience a UDP packet loss of around 5-10% when running experiments on the DAS5 TU cluster. This is a high drop rate, considering a LAN environment. Removing the call to `setsockopt` results in no UDP packet drop. However, when increasing the workload (and therefore, the number of messages sent around), I suddenly started to experience UDP packet drop again. Setting the UDP buffer size to `262144 * 2` seems to decrease the loss to 0% again.

Therefore, I think that the value of `socket.SO_RCVBUF` is application-specific. By default, this is set to the value written in `/proc/sys/net/core/rmem_default`, which on the DAS5 is `2 ** 18 = 262144`. I'm not sure about the best value but it seems that setting the buffer to `UDP_MAX_SIZE` does result in packet loss, at least on the DAS5. This effect might also be observable when doing anonymous downloads where we potentially have a large number of incoming UDP packets in a short time, quickly filling the buffers.

I think we should: 1) make `socket.SO_RCVBUF ` tunable per application, and 2) demise on a reasonable value for `socket.SO_RCVBUF` for Tribler, preferably derived from some experiments.

**Comment by qstokkink** [comment]
Part of what I want to do with #615 (allowing for multiple interfaces per peer) is using a reserved control message socket and a high-throughput socket, tuned accordingly.

If you want to do custom tuning, just feed IPv8 your own Endpoint subclass (this is already possible).

That said, having the exact buffer sizes we require before making these changes is of course a good idea 👍

**Comment by qstokkink** [comment]
Since you can give IPv8 a application-tuned Endpoint on startup, I think this issue is sufficiently solved. 
For out-of-the box network layer abstraction, I think #615 is sufficient to cover the issue at hand.

**Comment by devos50** [comment]
I guess it's also addressed already by https://github.com/Tribler/py-ipv8/commit/5104aec164de2ffdc90aa955b939db27f954da79
