### ISSUE TITLE
Unable to follow the " first overlay" tutorial

### ISSUE THREAD

**Issue by n9iels** [Tribler/py-ipv8#698]
## Summary
I am trying to follow the [Creating your first overlay](https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial) tutorial but I am running into a few issues. For the first sections anything seemed to be find, however for the "Printing the known peers" section I only got the following output:
```
I am: Peer<0.0.0.0:0, /zWXEA/4wFeGEKTZ8fckwUwLk3Y=>
I know: []
I am: Peer<0.0.0.0:0, VVsH+LxamOUVUkV/5rjemqYMO8w=>
I know: []
```
so the `[]` of known peers is always empty. I let the program ran for a few minutes. A close inspection of the logs for the previous sections also indicates that something is going wrong. It gives me the following output:
```
INFO:HiddenTunnelCommunity:Could not create circuit, no available exit-nodes
```
I am completely new to this project and all the knowledge behind it, so currently I'm trying to familiarize me with it. I was wondering if you could tell what's going on and if you can point me in the right direction to fix it. Many thanks in advance! :smile: 

## Used software
- `master` branch of py-ipv8
   - All tests pass
- Ubuntu 18.04
- Python 3.7.5
- Pip 9.0.1

**Comment by qstokkink** [comment]
Thank you for your interest in IPv8, I'll look into this issue:

- I can reproduce this.
- I verified the tutorial still works with the previous `1.10` release. For now, I can at least say it happened due to the switch to the new `asyncio` backend.
- I'll narrow down on the problem and fix it asap.

**Comment by qstokkink** [comment]
## Core issue

https://github.com/Tribler/py-ipv8/blob/5104aec164de2ffdc90aa955b939db27f954da79/ipv8/messaging/interfaces/udp/endpoint.py#L62

`create_datagram_endpoint` does not throw an error when reusing the same port. This causes both IPv8 instances in the tutorial to think they own the same port.

## Temporary fix

Assign a custom `port` entry in each IPv8 instance. For example:

```python
for i in [1, 2]:
    configuration['port'] = 8090 + i
```

**Comment by n9iels** [comment]
Thanks for the fast response! I've tried both your temporary fix, the fix in the pull request and a combination of them, however I still have the same issue. On a interesting note, the `no available exit-nodes` also keep popping up when when starting one IPv8 instance only (first section of the tutorial).

**Comment by qstokkink** [comment]
Interesting, then I can no longer reproduce your issue. Could you try adding the following lines to your `Community` subclass of the peer printing overlay code?

```python
    def introduction_request_callback(self, peer, dist, payload):
        print(payload)

    def introduction_response_callback(self, peer, dist, payload):
        print(payload)
```

You *should* see a lot of stuff printed, including at least one line that has an entry `source_lan_address: ('your LAN IP here', 8090)`.

**Comment by qstokkink** [comment]
Also, don't forget to update to the latest `master`.

**Comment by n9iels** [comment]
I am running the latest `master` and added your suggested lines of code to the `Community` class (The `MyCommunity` class from the code snippet in the tutorial)`. Neither a address with the port 8090 or my own LAN/WLAN IP is printed. Does this mean that it somehow cannot bind to that port?

**Comment by qstokkink** [comment]
The complete output is probably not needed. However, could you verify that the printed output **does** include a lot of lines with `destination_address: ('your IP here', 8090)`?

Possibly switching the configuration to `DEBUG` will show some more in-depth information, should there be a binding problem:

```python
configuration['logger'] = { 'level': "DEBUG" }
```

**Comment by n9iels** [comment]
I've switched the logging level to `DEBUG`. When starting the [snippet](https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial/#printing-the-known-peers) it initially gives me the error that listening on `8090` is not possible. When adding the custom port mapping (eg. `configuration['port'] = 8090 + i`) the output looks something like this:
```
DEBUG:MyCommunity:Launching MyCommunity with prefix b'00024513fa656d11ef4c2c521765af17dde3a0c38086'.
DEBUG:UDPEndpoint:Listening at 8091
I am: Peer<0.0.0.0:0, WYg7V5Qf0TkEzgJH2x/eRqHHg2c=> 
I know: []
DEBUG:MyCommunity:Launching MyCommunity with prefix b'00024513fa656d11ef4c2c521765af17dde3a0c38086'.
DEBUG:MyCommunity:Bootstrapping MyCommunity, current peers 0
DEBUG:UDPEndpoint:Listening at 8092
I am: Peer<0.0.0.0:0, FFzmZIjr6gME79F7EgSGMOhIJhs=> 
I know: []
DEBUG:MyCommunity:Bootstrapping MyCommunity, current peers 0
IntroductionResponsePayload
| connection_type: 'unknown'
| destination_address: ('217.100.28.67', 61325)
| extra_bytes: b''
| identifier: 4
| lan_introduction_address: ('0.0.0.0', 0)
| source_lan_address: ('131.180.27.156', 6424)
| source_wan_address: ('131.180.27.156', 6424)
| tunnel: False
| wan_introduction_address: ('0.0.0.0', 0)
```

There is no line with my IP address and a port in the `80xx` range. None of the listed IP addresses are somehow familiar to me. I honestly think this is a OS related issue... Many thanks for the reponse btw :)

**Comment by qstokkink** [comment]
You should only have to run it. Without any edits and on the latest `master` I get the following output ([for this snippet](https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial/#printing-the-known-peers)):

```
$ python3.7 main.py
I am: Peer<0.0.0.0:0, nvqouJylNS0Skt2ZtnfoDb2vaxg=> 
I know: []
I am: Peer<0.0.0.0:0, eLFxLN0yYvS5MI6tCaSXbSUTOKo=> 
I know: []
I am: Peer<0.0.0.0:0, nvqouJylNS0Skt2ZtnfoDb2vaxg=> 
I know: ['Peer<192.168.178.248:8091, eLFxLN0yYvS5MI6tCaSXbSUTOKo=>']
I am: Peer<0.0.0.0:0, eLFxLN0yYvS5MI6tCaSXbSUTOKo=> 
I know: ['Peer<192.168.178.248:8090, nvqouJylNS0Skt2ZtnfoDb2vaxg=>']
I am: Peer<0.0.0.0:0, nvqouJylNS0Skt2ZtnfoDb2vaxg=> 
I know: ['Peer<192.168.178.248:8091, eLFxLN0yYvS5MI6tCaSXbSUTOKo=>']
I am: Peer<0.0.0.0:0, eLFxLN0yYvS5MI6tCaSXbSUTOKo=> 
I know: ['Peer<192.168.178.248:8090, nvqouJylNS0Skt2ZtnfoDb2vaxg=>']
```

**Comment by qstokkink** [comment]
That reminds me, do you have IPv4 enabled?

**Comment by qstokkink** [comment]
The output you posted also suggests there are no issues.

The only thing I can think of at this point is that you mentioned your IP was not in the listed output (specifically `217.100.28.67` should be shown by https://www.whatismyip.com/).

**Comment by n9iels** [comment]
I can now confirm this is a issue related to my machine only. I created a VM (Ubuntu 18.04.3 (LTS) x64) and followed the tutorial. I was able to run the "Printing the known peers" snippet without any problems.

Thanks for the help and fast response! I will try to narrow this issue down on my machine, if I find the cause and it is worth to mention I will let you know.

**Comment by qstokkink** [comment]
Good to hear. If you figure out what was going on, please let us know so we can mention this in the documentation for future first-timers.
