### ISSUE TITLE
Custom network overlay does not work for all ip addresses

### ISSUE THREAD

**Issue by n9iels** [Tribler/py-ipv8#703]
## General
After having troubles with following the "Creating your first overlay" tutorial (see: https://github.com/Tribler/py-ipv8/issues/698) I noticed that my laptop was not able to find any peers on the office network, but that it was working at my home network. The main difference is that my home network gives my laptop a IP in the range of `192.168.2.x`, while the office network gives my laptop a IP in the range of `10.x.x.x`. I can also reproduce this issue when using a mobile hotspot which gives me a IP in t he range of `192.168.43.x`.

## Reproducing the issue
1. Implement the ["Printing the known peers"](https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial/#printing-the-known-peers) section of the "Creating your first overlay" tutorial
2. Verify that the output is as expected (the described output in the tutorial)
3. Connect to a mobile hotspot
4. Re-run the script and verify that no peer could be found anymore

## System information
- Latest version of master (`f9afbb94f710717b6cf40e1a228cb3168dd2ce68`)
- Python 3.7.5

**Comment by qstokkink** [comment]
Interesting, do you have `netifaces` installed?

**Comment by n9iels** [comment]
Yes, I used the provided `requirements.txt` and I verified that the corresponding methods are used. For example in `endpoint.py` the `get_lan_address_without_netifaces()` method is not used.

**Comment by qstokkink** [comment]
Reproducing this will probably take a little while, sounds like an issue with the type of NAT (though it really *should* work). At some point we'll have to [patch up and systematically test configurations with our NAT setup](https://github.com/Tribler/tribler/issues/2754#issuecomment-404807341). I'll try to reproduce your setup and hope the problem occurs.

@synctext official request for another student on NAT traversal 😃

**Comment by qstokkink** [comment]
I actually managed to reproduce this today. For some reason the WAN->LAN address translation/estimation is broken when two machines are behind the same WAN address.

**Comment by qstokkink** [comment]
This should have been fixed by #1133, at least to the point that it _can_ reasonably _be_ fixed by IPv8's NAT puncturing approach. Different approaches than the current one are discussed in https://github.com/Tribler/tribler/issues/2754 (superseding this issue).
