### ISSUE TITLE
Ability to verify if a attestation is made by a certain peer

### ISSUE THREAD

**Issue by n9iels** [Tribler/py-ipv8#706]
_note: This is a question about functionality, not a bug or issue with the code. Please let me know if there is another channel where these kind of questions should be asked_

Given a situation where there are three peers, say for example a bank, customer and the CJIB (Centraal Justitieel Incassobureau). The customer can ask the CJIB to attest a `i_have_no_debt` claim, the bank can ask the customer to present this attested claim in order to provide a loan. 

If I follow the [Attestation Tutorial](https://py-ipv8.readthedocs.io/en/latest/basics/attestation_tutorial/) I understand that one peer can ask another peer to verify if he has an attribute with a certain value. However, in my fictional situation I also want to verify if the attribute is attested by a specific peer (the CJIB). Is there a way to do this, or am I misunderstanding this tutorial?

If your are interested, I wrote down the flow [over here](https://github.com/Quintor/discipl-core-ipv8/blob/docs/exampe-flow/docs/example-attestation-flow.md).
Many thanks in advance!

**Comment by qstokkink** [comment]
The `GET http://localhost:14410/attestation?type=attributes` can also be fed a `mid=..` to check the attester (attestor in your flow) of attributes other peers have (in this version of the code, you get to see all attributes of other peers -- in a commercial setting you need be given permission).

You will need to match the attester id of the attribute with either (1) your external DPKI or (2) the ephemeral peer id of the attester you just verified access rights for using IPv8,  to make sure it is still the correct peer (CJIB in your case).

**Comment by n9iels** [comment]
> The GET http://localhost:14410/attestation?type=attributes can also be fed a mid=.. to check the attester (attestor in your flow) of attributes other peers have

Can you explain this a little bit more? For example if I call `http://localhost:14410/attestation?type=attributes&mid=0Jwy2oSmkJFmR22MexNzZW7bSus%3D` it should give all attributes of the peer on 14410 attested by `0Jwy2oSmkJFmR22MexNzZW7bSus%3D`. (this is not the case so I think I am wrong here)

**Comment by qstokkink** [comment]
> Can you explain this a little bit more? For example if I call http://localhost:14410/attestation?type=attributes&mid=0Jwy2oSmkJFmR22MexNzZW7bSus%3D it should give all attributes of the peer on 14410 attested by 0Jwy2oSmkJFmR22MexNzZW7bSus%3D. (this is not the case so I think I am wrong here)

No this would give all the attributes of `0Jwy2oSmkJFmR22MexNzZW7bSus%3D` as known by the peer on `localhost:14410` (customer). Useful for hierarchical DNS-like permission/authorization, but not what you want right now.

You would do (1) a `GET http://localhost:14411/attestation?type=attributes&mid=aQVwz9aRMRypGwBkaxGRSdQs80c%3D` as the CJIB to verify the existence of the attribute on the client and (2) verify that `0Jwy2oSmkJFmR22MexNzZW7bSus%3D` (the CJIB itself) is the attester.
