### ISSUE TITLE
500 error when trying to get trustchain blocks

### ISSUE THREAD

**Issue by n9iels** [Tribler/py-ipv8#709]
## General
When you try to get the most recent trustchain blocks via the REST API (http://localhost:14411/trustchain/recent) the server response with a 500 Internal Server Error and the error message:
```
File "/home/niels/Documents/ipv8/pyipv8/ipv8/messaging/deprecated/encoding.py", line 210, in _a_decode_unicode
    return offset + count, stream[offset:offset + count].decode("UTF-8")
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
```
When trying to receive the blocks of a specific user (http://localhost:14411/trustchain/users/pub_key/blocks) the server also responds with a 500 Internal Server Error and the error message:
```
File "/home/niels/Documents/ipv8/pyipv8/ipv8/messaging/deprecated/encoding.py", line 210, in _a_decode_unicode
    return offset + count, stream[offset:offset + count].decode("UTF-8")
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
```
As far as I understand it goes wrong when decoding the `transaction` part/key of a block on this line: https://github.com/Tribler/py-ipv8/blob/master/ipv8/attestation/trustchain/block.py#L513

## Steps to reproduce
1. Follow the "Enrollment/Attestation flow" section of the [Attestation Tutorial](https://py-ipv8.readthedocs.io/en/latest/basics/attestation_tutorial/#enrollment-attestation-flow)
2. Go to the above urls and confirm the response is a 500 Internal Server Error

**Comment by qstokkink** [comment]
That's a new one. Could you add a `print(repr(self.type), repr(self._transaction))` before https://github.com/Tribler/py-ipv8/blob/master/ipv8/attestation/trustchain/block.py#L513, to give us some more information?

**Comment by n9iels** [comment]
Sure :) See the output below:
```
b'id_metadata' b'a4d4bhash20b\xe3\xaf\xcf3\xb5lY}\xccq\xc6\x18\x07\xd4X\x00+xJ{4bname12smy_attribute4bdate17f1584696254.2566328bmetadata0d'
```

**Comment by qstokkink** [comment]
Ah, I see. Thanks. Another Python 3 switch bug. I'll patch this momentarily.
