### ISSUE TITLE
[question] Send non-public data along with an attestation request

### ISSUE THREAD

**Issue by n9iels** [Tribler/py-ipv8#728]
Imagine a situation where a peer requests attestation for a attribute, but in order to get attestation it needs to provide some private additional data. What would be the best way to send this data with the attestation request in way that only the attester can see it?

My initial idea was the `metadata` field, however this appears to be exposed in the trustchain en thus cannot contain private data. Another idea I had was to put the data in a self-attested claim, however the creation of this claim seems not to be possible. Also the `verify` step is relying on the fact that the other party already knows the content of a claim.

Is there a way to do this, or I my idea out of scope for the functionality and general goal of IPv8?
Many thanks in advance!

**Comment by qstokkink** [comment]
We had the same idea when we started out, but dropped it.

Long story short: there is a business logic flow and there is the IPv8 attestation functionality and they should not mix. Both (1) the prerequisites before attestations are made and (2) the identifier of the peer that is communicated with should be handled through a covert channel in the business logic layer. This could (for example) be in an HTTPS session. In our experience, this separation of concerns makes for the simplest interactions between peers (and makes it harder to make mistakes 😃 ).

> Is there a way to do this, or I my idea out of scope for the functionality and general goal of IPv8?

Concluding, for REST API driven functionality: yes it is out of scope.

However the story does not end there: IPv8 is not just about the attestation REST API. There is an IPv8-only way to do this: that is by integrating your business logic into an IPv8 overlay design, for which you can make your own REST API bindings. That is, however, a bit more advanced use of IPv8 than simply making some REST calls (but we have a [ReadTheDocs page](https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial/) on this nonetheless, if you are feeling particularly brave). I would recommend sticking with the HTTPS approach if you can though.

**Comment by n9iels** [comment]
Thanks for you reply :smiley: We will think about a way to implement this in our business logic.
