### ISSUE TITLE
Verification output endpoint show verifications that are in progress

### ISSUE THREAD

**Issue by n9iels** [Tribler/py-ipv8#742]
The endpoint `attestation?type=verification_output` shows verifications that are still in progress. The issue is that those verifications always have a `match` value of `0`. So when the endpoint is called during the verification process the result might indicate that the verification faild, but it is still in progress and a few ms later the `match` value could be different.

I noticed this behavior when writing integration test. The time between `verify`, `allow_verify` and `verification_output` is extremely short since they are right after each other. In more "normal" use cases I never encountered this issue.

**Comment by qstokkink** [comment]
Thanks for the feedback, I have added this to the ID refactoring ticket (#733).

Some context:
The REST API bindings are over 2 years old and were made when the identity project was first launched. The API has been frozen in time to avoid breaks with our (super secret) downstream projects. I'll be engineering a `v2` API that includes quality-of-life improvements --such as yours-- and proper REST resources.
