### ISSUE TITLE
IPv8 forgets all peers when using RandomChurn

### ISSUE THREAD

**Issue by TimSpeelman** [Tribler/py-ipv8#743]
When running multiple IPv8 instances as prescribed in the attestation tutorial, in some cases peers never find other peers at all. In other cases, they find some peers, but after less than a minute, the list of known peers is empty again.

I have queried the list of empty peers using `GET http://localhost:14411/attestation?type=peers`.

EDIT: The problem is gone when I disable RandomChurn.

**Comment by qstokkink** [comment]
I cannot reproduce this. Could you add a debug statement after this line https://github.com/Tribler/py-ipv8/blob/master/ipv8/community.py#L329 :

```python
print(probable_peer, handler)
```

Also, could you verify no errors are printed?

**Comment by qstokkink** [comment]
I ran your particular script for over 20 minutes without issues on Ubuntu 19.10. What operating system are you using?

**Comment by TimSpeelman** [comment]
I cannot reproduce this myself either.
