### ISSUE TITLE
create_test_coverage_report still using Twisted

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#744]
The `create_test_coverage_report.py` script still uses Twisted. This should be switched to `asyncio`.

**Comment by qstokkink** [comment]
This also causes the GitHub frontpage build failures. Uh oh.

**Comment by egbertbouman** [comment]
It's a bit weird that this script not using `asyncio` causes the builders to fail. Especially since they seemed to be running fine before. I guess some of the newer tests don't work well with Twisted?

**Comment by qstokkink** [comment]
I believe Twisted has its own overwrite for `setUpClass`, making this code incompatible:

https://github.com/Tribler/py-ipv8/blob/52e314cb47b669cda7bcab8dc78028a77bc1788e/ipv8/test/attestation/tokenchain/test_token.py#L10

So by using the old Twisted testing suite (without calling the Twisted `setUpClass`) it doesn't work.
