### ISSUE TITLE
Defer I/O to a separate process

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#752]
IPv8 has as many threads as it has branches: only one.

This single thread approach also means that any nasty operations (like file I/O) on the main thread block all other events (most notably packets will be dropped by the socket).

Today I decided to investigate the impact of deferring file I/O to a separate process on the *responsiveness* of periodic calls. The experiment setup consists of two asynchronous calls:
 - A measuring call attempting to sleep for 0.01 seconds continuously.
 - A call making 3 batches of file writes. Each batch contains 500 files and uses a different writing strategy.

The strategies are as follows:
 1. Await an `asyncio.gather` of all 500 file writes performed by a different process.
```python
await asyncio.gather(write1(), write2(), write3(), ... )
```
 2. Sequentially await all 500 files writes performed by a different process.
```python
await write1()
await write2()
await write3()
...
```
 3. Run all 500 file writes in the call itself.
```python
with open(file1, "wb") as f:
    f.write("something")
with open(file2, "wb") as f:
    f.write("something")
...
```

The measuring call measures the time it takes beyond the 0.01 seconds for control to return to it, which I called *drift*. A drift of 0.01 seconds would mean that the requested 0.01 second sleep took 0.02 seconds. I plotted the drift as the writing call went through the three strategies - white shading signifies the waiting time between starting and completing the 500 file writes:

![clock_drift](https://user-images.githubusercontent.com/3630389/83891646-cbb24600-a74d-11ea-9ffb-7f66eaa223ec.png)

### Findings

 - Never ever use `gather` to batch file I/O offloading.
 - If you want speed and don't care about other event handling, run everything on the main thread using the normal file I/O.
 - If you want to remain responsive to other events, sequentially offload (i.e. `await` each write on demand) your file I/O to another process. This is slower however.

### Conclusion
Offloading I/O to a separate process has its place and time. As IPv8 is event-based, it would pay off to offload I/O to another process under heavy load to remain responsive to events. Future work consists of checking if this holds for all I/O - most importantly the database I/O.

**Comment by egbertbouman** [comment]
From what I understand in strategy 1 you create 500 tasks more or less at the same time, so more drift seems to be expected. In strategy 2 you create 1 task at a time, so obviously there is less drift. Besides strategy 3, where you block the `asyncio` thread, perhaps you could also try making the write calls non-async and using an executor:
```python
await loop.run_in_executor(None, write1)
````

In combination with `gather` (untested):
```python
tasks = [loop.run_in_executor(None, f) for f in [write1, write2, ...]]
await asyncio.gather(*tasks)
```

**Comment by qstokkink** [comment]
Thanks for the suggestions, I'll try those out.

> Although, depending on your experiment, you're probably better of to just call the write functions sequentially within the executor.

I think that for all sporadic file use you're indeed actually better off on the main thread.

I'm specifically exploring high-volume small read/write applications now for use cases such as _database I/O on introduction requests/responses_. A growing demand for this is emerging from our downstream projects (e.g. Trustchain). I'd like to support those natively from IPv8, so we don't get 50 different custom solutions.

**Comment by qstokkink** [comment]
First things first though: I'll make a REST endpoint to measure the congestion of the main thread. I'll hook it into the Tribler debug panel to see how bad this problem is in practice (or if I'm fixing something that isn't broken 😃).

**Comment by egbertbouman** [comment]
> I think that for all sporadic file use you're indeed actually better off on the main thread.

You're right, but in this case of 500 writes I was suggesting running all writes sequentially on a separate thread (by default, an `asyncio` executor is basically a way to offload to the thread pool).

We already use executors to connect to the database from within message handlers in [Tribler](https://github.com/Tribler/tribler/blob/337ae8e6e390ad216861a0e6265989bebf232e2d/src/tribler-core/tribler_core/modules/popularity/popularity_community.py#L84). This will hopefully alleviate problems with high drift. However, the code in Tribler doesn't look very nice, and I've been thinking of adding an async contextmanager to make it a bit cleaner. Perhaps this code should be in IPv8 instead.

Also, in case we find it's still better to do stuff in a separate process, I would suggest using `concurrent.futures.ProcessPoolExecutor`. It offers the same functionality as the `concurrent.futures.ThreadPoolExecutor`, but in a separate process. Although I think this kind of logic is more meant for running CPU bound code.

**Comment by qstokkink** [comment]
Having hooked in the REST endpoint in #753 and investigating main thread congestion, this doesn't seem to pressing of an issue. For now https://github.com/Tribler/tribler/pull/5353 should provide us with enough insight at runtime.

We can reopen this issue if it ever does become a significant issue.
