### ISSUE TITLE
Supplement merge builders (front page) with mutation testing

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#778]
[Idea proposed by @synctext]

We can get a feel for the quality of the tests of IPv8 by running a mutation testing pass (with for example https://pypi.org/project/MutPy/) every time a commit is merged into the `master` branch. As this is highly randomized, this should not be part of the normal PR tests, but only part of the checks on merge (see the build statuses on the IPv8 GitHub front page/README). This complements the coverage check for said builders.

**Comment by qstokkink** [comment]
MutPy works quite well, and has some appealing output:

![afbeelding](https://user-images.githubusercontent.com/3630389/86465989-14502580-bd33-11ea-9074-3ab833bf9db2.png)

The project also seems unmaintained and has some issues (like loading external content from a `.com` address in the report).
If we continue with this, we should make our own fork of MutPy that we maintain for our own purposes.

**Comment by qstokkink** [comment]
Step 1 complete (thanks @devos50 for hooking me up with a container): I have modified MutPy to my liking. Mainly I made all of the buttons work, allowed the report to be viewable offline and made each mutation only show the diff instead of the whole file:

![afbeelding](https://user-images.githubusercontent.com/3630389/86479718-fbed0480-bd4c-11ea-96c2-3285164562e8.png)

The next step will be to create a Python script that iterates over all test files in IPv8 and launches our custom MutPy for each combination of test file and class under test.

After that I will make a script that combines all of the outputs into a single report.

The final step will be hooking this all up into Jenkins to run with the merge builders on the front page.

**Comment by qstokkink** [comment]
Observation: this is way to slow to even run on merge. This should be a daily build instead.

**Comment by qstokkink** [comment]
Here is the output of the very first full IPv8 mutation test, completing in exactly 3 hours and 40 minutes:

Legend:
 - Green: test failed assertion (this is good).
 - Red: test missed mutation (this is bad).
 - Blue: test timed out due to mutation (this is kind of good).
 - Yellow: the mutation caused a syntax or import error (no information).

![afbeelding](https://user-images.githubusercontent.com/3630389/86493979-e3dcab80-bd73-11ea-9e98-206fd7757ea1.png)

**Comment by synctext** [comment]
very impressive stuff!
Did you evaluate other Python package before settling for this one?

**Comment by qstokkink** [comment]
> Did you evaluate other Python package before settling for this one?

No:

There are two other big mutation testing packages. One is [mutmut](https://pypi.org/project/mutmut/). But [some initial research showed](https://nedbatchelder.com/blog/201903/mutmut.html) that its output and extent is not exactly on the level of `MutPy`. The one thing that is nicer in `mutmut` is that it has `JUnit XML` support.

The other big one is [cosmic-ray](https://pypi.org/project/cosmic-ray/). I'm not sure what to make of this one from existing documentation and reviews, it wasn't as straightforward as `MutPy`. It might be great and it might be trash. This one could use further investigation, but I didn't want to allocate that much of my time.

**Comment by qstokkink** [comment]
Of course I welcome anyone to perform an in-depth analysis of the other mutation testing frameworks. My aim here was just to produce something that works, not necessarily to provide a comprehensive evaluation of all frameworks.

**Comment by qstokkink** [comment]
We have a daily builder on Jenkins now producing a report:

https://jenkins-ci.tribler.org/job/ipv8/job/mutation_test_daily/lastSuccessfulBuild/artifact/

![](https://jenkins-ci.tribler.org/job/ipv8/job/mutation_test_daily/badge/icon)

The only remaining problem is that the website is not viewable from Jenkins itself correctly and you need to download the entire thing to view it. I'm not sure if that problem is worth solving though.
