### ISSUE TITLE
Allow for non-ascii URLs in TunnelCommunity payloads

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#803]
https://github.com/Tribler/py-ipv8/blob/5ba9031a381ef890526891507102e1e72d3bf385/ipv8/messaging/anonymization/payload.py#L32

This line uses `cast_to_bin` to convert `str` to ASCII URLs. This will not work for non-ASCII characters. Instead the `idna` should be used, as follows:

```python
idna_host = host.encode("idna")
return pack("!BH", ADDRESS_TYPE_DOMAIN_NAME, len(idna_host)) + idna_host + pack("!H", port) 
```

**Comment by egbertbouman** [comment]
Actually, I prefer to just encode using UTF-8. Also, note that `decode_address` is already decoding using UTF-8. So, existing nodes in the `TunnelCommunity` will already be compatible.

**Comment by qstokkink** [comment]
> So, existing nodes in the TunnelCommunity will already be compatible.

`idna` produces ASCII, there is no incompatibility.

**Comment by qstokkink** [comment]
Confirmed, this will also work:

```python
utf8_host = host.encode("utf-8")
return pack("!BH", ADDRESS_TYPE_DOMAIN_NAME, len(utf8_host)) + utf8_host + pack("!H", port) 
```

`idna` conversion is then performed by `socket` later when the hostname is resolved. This upside to this approach is that it is shorter on the wire than immediately applying `idna`.

**Comment by egbertbouman** [comment]
I never said there was an incompatibility. I said that, on the receiving end, existing nodes already allow for UTF-8 encoded hostnames.

I don't really see why you would encode using IDNA if you don't have to. After all, IDNA is basically a hack that allows for Unicode names, even if the underlying protocol don't support this. Only that the exit do we *need* to encode using IDNA, and that is done automatically by Python.

**Comment by qstokkink** [comment]
> I never said there was an incompatibility. I said that, on the receiving end, existing nodes already allow for UTF-8 encoded hostnames.

You left that out, so I added to your information. My message is that both approaches will work.

> I don't really see why you would encode using IDNA if you don't have to. After all, IDNA is basically a hack that allows for Unicode names, even if the underlying protocol doesn't support this.

Because, right now, IPv8 will crash when encountering a utf-8 string.

Also, there is no such thing as a utf-8 URL. Whether you apply IDNA now (sending through the tunnels) or later (at the exit node) doesn't actually matter. But, at some point IDNA will be applied anyway -- because a utf-8 URL does not exist.

**Comment by egbertbouman** [comment]
> My message is that both approaches will work.

Yes, of course. It's about whether hostnames should be ASCII or UTF-8 encoded.

> Because, right now, IPv8 will crash when encountering a utf-8 string.

Clearly there is a bug. I'm not disputing that.

>Also, there is no such thing as a utf-8 URL.

We talking about encoding hostnames using UTF-8 in the tunnel protocol.

**Comment by qstokkink** [comment]
> I'm just saying I prefer UTF-8 encoding instead of IDNA.

I looked at what you said and I agree 😃! Let me quote myself:

> This upside to this approach is that it is shorter on the wire than immediately applying idna.
