### ISSUE TITLE
AttributeError: 'PexMasterPeer' object has no attribute 'public_key'

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#805]
When querying the peers in an overlay, using the `/ipv8/overlays` endpoint, I get the following response:

```
{
    "error": {
        "code": "AttributeError",
        "handled": false,
        "message": "'PexMasterPeer' object has no attribute 'public_key'"
    }
}
```

It seems that the `PexMasterPeer` only has a mid (the infohash of the hidden swarm), and not a public key attribute.

**Comment by devos50** [comment]
@egbertbouman could you have a look at this?

**Comment by egbertbouman** [comment]
Sure, will do.

**Comment by qstokkink** [comment]
In this case we should modify https://github.com/Tribler/py-ipv8/blob/master/ipv8/REST/overlays_endpoint.py.

We have multiple Communities now (also in the Kotlin implementation) where the community ID is not actually the `SHA-1` of any key.

**Comment by qstokkink** [comment]
In the future I'd also like to get rid of the master `Peer` altogether for that reason and just switch to a 20 byte community ID.

**Comment by egbertbouman** [comment]
@qstokkink That would be really nice. After looking through the code a bit, only the `OverlaysEndpoint` seems to be using it. Instead of working around a missing `master_peer.public_key`, we could just go ahead and replace `master_peer` with a byte-string.

**Comment by devos50** [comment]
Could we consider a short-term fix for this instead of replacing the `master_peer` (not sure how much time this will take)? I'm currently debugging the exit nodes and there seems to be something weird going on with the verified peers there. I'm unable to query the overlay peers because of this error, making it hard to debug further 😢 

That said, I'm all in favour of replacing the `master_peer` with a byte-string 👍

**Comment by egbertbouman** [comment]
@devos50 Fair enough, I just made a PR to fix the `OverlaysEndpoint`.
