### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'future'

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#806]
I noticed this error when closing Tribler (current devel branch):

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8/taskmanager.py", line 131, in done_cb
    future.result()
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8/taskmanager.py", line 18, in interval_runner
    await task(*args)
  File "/Users/martijndevos/Documents/tribler/src/tribler-core/tribler_core/modules/bootstrap.py", line 60, in fetch_bootstrap_peers
    nodes = await self.dht.connect_peer(bytes(unhexlify(mid)))
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8/dht/discovery.py", line 110, in connect_peer
    nodes = await self.send_connect_peer_request(mid, nodes[:TARGET_NODES])
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8/dht/discovery.py", line 125, in send_connect_peer_request
    futures.append(cache.future)
AttributeError: 'NoneType' object has no attribute 'future'
```

**Comment by egbertbouman** [comment]
It looks like `RequestCache.add` is returning `None`, which can happen if the `RequestCache` is already shutdown. To prevent issues like this, we shut down all `DHTCommunity` tasks before shutting down the `RequestCache`.

However, in this case, it looks like another Tribler component (`Bootstrap`) is calling the `DHTCommunity` after shutdown.

**Comment by devos50** [comment]
Good point. It seems that `Bootstrap` is shutdown correctly but I guess a call to `fetch_bootstrap_peers` could get through after IPv8 already shutdown everything. We could shutdown `Bootstrap` before IPv8 to address this then I guess?

**Comment by egbertbouman** [comment]
That should fix it, yes.

**Comment by qstokkink** [comment]
Is this a Tribler bug then?

**Comment by devos50** [comment]
Partially, it can be fixed in both IPv8 and Tribler.

I fixed the Tribler part in https://github.com/Tribler/tribler/pull/5448

**Comment by egbertbouman** [comment]
Do we want the `DHTCommunity` to be able to gracefully handle requests after shutdown? If so, I'll have to add if-statements in all functions that can be called externally.

**Comment by devos50** [comment]
@egbertbouman it would make the `DHTCommunity` more robust against this kind of errors when shutting down. However, I also think that the fix in Tribler (earlier shutdown of the `Bootstrap` class) should sufficiently address this issue. Furthermore, errors during shutdown are usually not affecting the end-user too much. I'll leave it up to you 👍

**Comment by qstokkink** [comment]
Seeing as we explicitly chose to not use if-statements in the DHTCommunity before, I'll consider this issue resolved.
