### ISSUE TITLE
Infinite loop when receiving invalid block during crawl request when wanting to sign a block

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#83]
I found an infinite loop when a node A wants to create a new block with a counterparty B. Suppose that the latest block of the chain of A is invalid (possibly due to a software bug or he could have inserted this himself). Now, when A creates a new block with node B and B does not have the latest blocks in the chain of A, B will issue a crawl request. Now, A will send the invalid block to B, which B will _not_ insert in his database. While this is expected, the problem here is that B will now call the `process_half_block` method again and the process continues.

I've written the following test to confirm this:

```
    @twisted_wrapper
    def test_invalid_block(self):
        yield self.introduce_nodes()
        invalid_block = TestBlock(key=self.nodes[0].overlay.my_peer.key)
        invalid_block.signature = 'a' * 64
        self.nodes[0].overlay.persistence.add_block(invalid_block)

        his_pubkey = self.nodes[0].network.verified_peers[0].public_key.key_to_bin()
        yield self.nodes[0].overlay.sign_block(self.nodes[0].network.verified_peers[0], public_key=his_pubkey,
                                               transaction={})

        yield self.deliver_messages()
```

@qstokkink any comments on this?

**Comment by qstokkink** [comment]
@devos50 nope

**Comment by qstokkink** [comment]
This is only half of the fix though. The peer which has this block in his database should also delete this junk, otherwise he will never be able to send blocks again.
