### ISSUE TITLE
Estimated WAN/LAN address is initialized with port 0

### ISSUE THREAD

**Issue by egbertbouman** [Tribler/py-ipv8#844]
After adding the `DispatcherEndpoint`, the `my_estimated_lan` / `my_estimated_wan` variables are initialized with port 0. This is making the hidden services test in Tribler fail.

The problem is that the initial port is only set correctly if the endpoint has a `_port` (which the `DispatchEndpoint` doesn't have):

https://github.com/Tribler/py-ipv8/blob/cb069df069328296d9d505f6513cfa67775aeaa5/ipv8/messaging/interfaces/endpoint.py#L128

When running Tribler normally, the `my_estimated_wan` recovers quickly, but the `my_estimated_lan` port stays at 0. This also means that we're sending an incorrect LAN address as part of the introduction-request/response messages.

**Comment by qstokkink** [comment]
This should be `self.endpoint.get_address()[1]` for the port. But that won't exist until the endpoint is actually open. Possibly we could make this a `@property` instead.

**Comment by qstokkink** [comment]
Something like (untested):

```python
@property
def my_estimated_lan(self):
    return (self._get_lan_address(True)[0], self.endpoint.get_address()[1] if self.endpoint.is_open() else 0)
```

**Comment by qstokkink** [comment]
Perhaps returning `("0.0.0.0", 0)` when the endpoint is closed is an even better option.

**Comment by qstokkink** [comment]
I'll cook up a fix.
