### ISSUE TITLE
The deadlock checker in the IPv8 tests is not compatible with pytest

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#864]
It seems that the custom deadlock detection logic in IPv8 does not play nicely with `pytest`. I am using the `pytest-flakefinder` tool to detect flaky tests in the Tribler core tests. This tool runs each test a specific number of times across different parallel worker processes. This work great for the tests that are exclusively using `pytest`. However, we have a few tests that are inheriting from IPv8, specifically the overlay tests for the popularity community and tunnel community.

Now, when running these tests with `pytest`, the worker process is killed after around 10 seconds into the `TestTriblerTunnelCommunity` tests. Setting the `MAX_TEST_TIME` to a higher value fixes this problem, however, it feels like a workaround and not a dedicated fix. It would be helpful if there is a feature to disable the deadlock checker for these Tribler tests.

**Comment by qstokkink** [comment]
> It would be helpful if there is a feature [...]

[Administrative notice] I edited the OP to fit the "Feature request" format.

**Comment by qstokkink** [comment]
`pytest` is not one of our supported testing suites, nor do I have any in-depth knowledge of it.

That said, I am not opposed to adding support for this, as long as it does not interfere with the 3 other testing suites.

What is the `pytest`-approved way of setting the class timeout value?

**Comment by devos50** [comment]
> What is the pytest-approved way of setting the class timeout value?

There is no notion of a class in `pytest`. Variables, such as the timeout value, is set in separate `.ini` files (see [here](https://github.com/devos50/tribler/blob/pytest/pytest.ini)).

**Comment by qstokkink** [comment]
So simply disabling the class timeout if pytest is loaded would be enough? Then this issue could be resolved with a single if-statement.

**Comment by devos50** [comment]
> So simply disabling the class timeout if pytest is loaded would be enough?

I think this makes sense since pytest has its own tools for deadlock detection/timeouts. I'm not sure how to detect if pytest is running the tests though.

**Comment by qstokkink** [comment]
Alright, I'll implement that. One moment.

Also, I'll use this to detect pytest: https://stackoverflow.com/a/44595269

**Comment by qstokkink** [comment]
Scratch that, we'll go with the official docs: https://docs.pytest.org/en/latest/example/simple.html#pytest-current-test-environment-variable
