### ISSUE TITLE
Error when getting LAN address without netifaces

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#868]
I was running some Tribler tests on a machine without `netifaces` installed, and I got the following error:

```
self = <ipv8.peerdiscovery.community.DiscoveryCommunity object at 0x7f292d4b37b8>
bootstrap = True

    def _get_lan_address(self, bootstrap=False):
        """
        Attempt to get the newest lan ip of this machine, preferably with netifaces, but use the fallback if it fails
        :return: lan address
        """
        if self._netifaces_failed:
>           return (self.get_lan_address_without_netifaces(), self.endpoint._port)
E           AttributeError: 'DispatcherEndpoint' object has no attribute '_port'

src/pyipv8/ipv8/messaging/interfaces/endpoint.py:290: AttributeError
```

Also see [here](https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_libtorrent_compatibility/601/console).

**Comment by qstokkink** [comment]
We have had a similar error before, resolved in the following way: https://github.com/Tribler/py-ipv8/pull/845/files#diff-901bef3cd0a7e5ef512f9710b66f780fR143

The fix for this issue is the same, the access to `endpoint._port` should be replaced with `self.endpoint.get_address()[1]`.
