### ISSUE TITLE
Add identity test Jenkins job

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#872]
The identity tutorial (https://py-ipv8.readthedocs.io/en/latest/basics/identity_tutorial/) describes a set of steps to achieve attribute attestation and verification. We could add a Jenkins job that verifies the described behavior.

**Comment by qstokkink** [comment]
For reference, I copied over the scripts I use for manual verification to Gist:

 - [Attestation test scripts ](https://gist.github.com/qstokkink/6f5bec769dae981a5eef67e57e6741a3)
 - [Deprecated Attestation test scripts](https://gist.github.com/qstokkink/33d988fb81053f6349aa35ddbec65a01)
 - [Other documentation tests](https://gist.github.com/qstokkink/32488e9a250649333b95aaa10886c4cb)

These should at some point be converted to automated Jenkins jobs (properly matching the outputs to what the tutorial claims). The 'other' documentation checks could possibly be automatically inserted into the documentation automagically through RST embedding.

**Comment by qstokkink** [comment]
The new attestation test script also still needs to integrate the advanced identity tools, given here: https://py-ipv8.readthedocs.io/en/latest/further-reading/advanced_identity/

**Comment by devos50** [comment]
You could consider integrating these jobs in [our validation experiment pipeline](https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiments/).

**Comment by qstokkink** [comment]
That seems like a good idea. We _should_ be able to make a configurable MultiJob that takes a `branch` argument, which we can then use to both test feature branches in IPv8 PRs and then also use for the IPv8 version shipped with Tribler (in that validation pipeline).

That will probably take some Jenkins-fu to correctly set-up though 😄

**Comment by qstokkink** [comment]
Before we tackle this, all code exmples should be first extracted into separate files: https://www.sphinx-doc.org/en/1.5/markup/code.html#includes
Otherwise we will need to maintain a duplicate per example.
