### ISSUE TITLE
Provide top-level types file

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#879]
Over the past few months I have been opportunistically adding typing to the codebase. However, one of the issues I have experienced with this approach is that to type functions, one needs to import the actual object. [This can lead to circular imports](https://www.stefaanlippens.net/circular-imports-type-hints-python.html) and beyond-top-level-import errors.

At this point in time, I see the ideal solution for this to be _conditional imports_ that are _only performed when checking types_: [PEP 563 Runtime annotation resolution and TYPE_CHECKING](https://www.python.org/dev/peps/pep-0563/#runtime-annotation-resolution-and-type-checking). If we provide all of the classes in IPv8 with an import-safe definition in a top-import-level `types.py`, we could have a circular-import-safe normal-typing-compatible way to statically type-check our code.

Practically, this should materialize as follows:

`ipv8/types.py`

```python
import typing

if typing.TYPE_CHECKING:
    # Absolute imports:
    from ipv8_service import IPv8
    from ipv8.database import Database
     ... et cetera ...
```

`ipv8/foo/bar.py`

```python
import ..types

def foo(ipv8: IPv8):
    return True
```

We can implement this incrementally and we should definitely start with a small part of the codebase first and evaluate this approach.

**Comment by qstokkink** [comment]
The following file already contain typing information and stand to benefit/need to change:

- `ipv8/configuration.py`
- `ipv8/peer.py`
- `ipv8/attestation/communication_manager.py`
- `ipv8/attestation/signed_object.py`
- `ipv8/attestation/identity/attestation.py`
- `ipv8/attestation/identity/community.py`
- `ipv8/attestation/identity/database.py`
- `ipv8/attestation/identity/manager.py`
- `ipv8/attestation/identity/metadata.py`
- `ipv8/attestation/schema/manager.py`
- `ipv8/attestation/tokentree/token.py`
- `ipv8/attestation/tokentree/tree.py`
- `ipv8/messaging/interfaces/dispatcher.py`

**Comment by qstokkink** [comment]
Slight change of plans, instead of actually performing absolute imports, we should use string literals as per PEP-0484: https://www.python.org/dev/peps/pep-0484/#forward-references .

```python
import typing

if typing.TYPE_CHECKING:
    Database = 'ipv8.database.Database'
    IPv8 = 'ipv8_service.IPv8'
    Key = 'ipv8.keyvault.keys.Key'
    Peer = 'ipv8.peer.Peer'
      ...
```

**Comment by qstokkink** [comment]
Memo 2: 

All files using this `TYPE_CHECKING` construction need `from __future__ import annotations`.

**Comment by devos50** [comment]
I also stumbled upon this issue when preparing https://github.com/Tribler/tribler/pull/5626. Quite annoying.

**Comment by qstokkink** [comment]
I'm still playing around with all the PEPs to find a sane resolution that runs, passes the linters and that allows all the static type checkers to work*. You can find my current best effort in #893, I'll keep you posted once I find an acceptable solution.

*Some solutions basically translate all of your custom types to `Any`, effectively voiding your typing.

**Comment by qstokkink** [comment]
Memo 3: Static type checkers don't care about circular imports when type checking.
