### ISSUE TITLE
The default IPv8 serialiser does not allow the serialisation of a (signed) long long value

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#881]
As the title says. For https://github.com/Tribler/tribler/pull/5626, I need to add a signed long long to a message, but there is currently no way to do so in the default IPv8 serializer. We can, however, serialized an unsigned long long value (`Q`).

I guess a signed long long would be `q`, see [here](https://docs.python.org/2/library/struct.html#format-characters).

**Comment by qstokkink** [comment]
For reference, you can always expose your own formats by calling `add_packing_format` on the default Serializer at module load time, in this case:

> default_serializer.add_packing_format('q', DefaultStruct(">q"))

As this is part of the default struct formats, it seems reasonable to add this to the defaults though.
