### ISSUE TITLE
Add shortcuts for node attributes in TestBase

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#897]
In many tests we assert that attributes of nodes change in a certain way (mostly their `overlay` attribute). We can adopt the style of `test_identity.py` in `TestBase` to provide convenient shortcuts:

https://github.com/Tribler/py-ipv8/blob/4843ff33b5eaf04c2315d04a1f40c5197fae0a11/ipv8/test/attestation/identity/test_identity.py#L21-L28

A before-and-after example:

```python
# Before
self.nodes[3].overlay.send_to(Peer(self.nodes[4].my_peer.public_key.key_to_bin(), self.nodes[4].endpoint.wan_address), 3)
self.assertEqual(3, self.nodes[4].overlay.something)
# After
self.overlay(3).send_to(self.peer(4), 3)
self.assertEqual(3, self.overlay(4).something)
```

**Comment by devos50** [comment]
Yes, this would be very convenient indeed 👍
