### ISSUE TITLE
Perform resolve_dns_bootstrap_addresses in daemon thread

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#903]
Currently `Community.resolve_dns_bootstrap_addresses()` blocks on the main thread using `socket.gethostbyname()`. Using `socket.gethostbyname()` was done to avoid resolution errors outside of the IPv8 control loop and should be kept. However, blocking on the main thread is not ideal.

Instead, `Community.resolve_dns_bootstrap_addresses()` can use a pop-up daemon thread to resolve the addresses and set `_DEFAULT_ADDRESSES` atomically (i.e. NOT appending each item to the `_DEFAULT_ADDRESSES` list, causing a concurrent modification exception).

**Comment by devos50** [comment]
I thought `asyncio` provides an asynchronous DNS lookup mechanism? You can have a look at the tunnel community logic to see how that's implemented 👍

**Comment by qstokkink** [comment]
Yes it does and I know how the TunnelCommunity does this, see also #726.

Essentially, internally, `asyncio` does the same as described above. However, we would then have to (1) deal with additional `Locks` to update the `_DEFAULT_ADDRESSES` dictionary and (2) make this method asynchronous.

**Comment by egbertbouman** [comment]
@qstokkink You can avoid the downsides of an `async` function by using the `task` decorator and avoid `Locks` by awaiting the result of `getaddrinfo` and updating the `_DEFAULT_ADDRESSES` dictionary on the main thread.
Then again, using a thread works too 🤷

**Comment by qstokkink** [comment]
@egbertbouman thanks for the suggestion and normally I would do it like you suggested. In this very specific case though, I did not want any registered tasks in the TaskManager: cancelling name lookups has historically been nasty and I wanted a method that is 100% in our own hands (no Twisted, no asyncio) and always works. After the umpteenth time of fixing deferred resolution I even made it block on the main thread.
