### ISSUE TITLE
Trustchain move to anydex-core

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#908]
Our old Trustchain implementation is moving to the anydex-core repository, the files that will need changes are:

 - [x] `ipv8_service.py`
 - [x] `doc/index.rst`
 - [x] `doc/basics/crawler_service_tutorial.rst`
 - [x] `doc/further-reading/trustchain.rst`
 - [x] `doc/reference/configuration.rst`
 - [x] `ipv8/attestation/trustchain/` remove entirely
 - [x] `ipv8/attestation/wallet/community.py`
 - [x] `ipv8/messaging/deprecated` remove entirely
 - [x] `ipv8/REST/attestation_endpoint.py`
 - [x] `ipv8/REST/root_endpoint.py`
 - [x] `ipv8/REST/trustchain_endpoint.py`
 - [x] `ipv8/test/attestation/trustchain/` remove entirely
 - [x] `ipv8/test/mocking/ipv8.py`
 - [x] `ipv8/test/test_configuration.py`
 - [x] `scripts/exitnode_ipv8_only_plugin.py`
 - [x] `scripts/trustchain_crawler_plugin.py`
 - [x] `systemd/trustchain-crawler.service`

**Comment by devos50** [comment]
You can probably also remove [the encoding implementation](https://github.com/Tribler/py-ipv8/blob/master/ipv8/messaging/deprecated/encoding.py) since I will use JSON serialization for transactions within blocks instead (if this encoding is not used anywhere else in IPv8).

**Comment by devos50** [comment]
I merged TrustChain into AnyDex in https://github.com/Tribler/anydex-core/pull/55. When we are sure that we are not making another 7.5.x release, you can safely remove TrustChain from IPv8 👍

**Comment by qstokkink** [comment]
Nice 👍 I will probably strip this out for the big 3.0 release then, when we also add IPv6 support.

**Comment by qstokkink** [comment]
As this touches a lot of files, I'll tag this as "on hold" until #615 is resolved.

**Comment by qstokkink** [comment]
Instead of waiting for #615, this issue will be `on hold` until the Tribler 7.6.0 official release (officially ending the downstream dependency on the deprecated Trustchain protocol).

**Comment by qstokkink** [comment]
This issue is now out of lockdown as Tribler 7.6.0 has been released.

**Comment by devos50** [comment]
> out of lockdown

It's a bit sad that this issue gets earlier out of lockdown than the Tribler developers 😢
