### ISSUE TITLE
Replace a bootstrap node

### ISSUE THREAD

**Issue by xoriole** [Tribler/py-ipv8#915]
With the recent changes expected in the infrastructure, the following bootstrap addresses needs to be changed in the next release.

https://github.com/Tribler/py-ipv8/blob/6eac51d611ab6e06b54622d5f9ab57782dd57a23/ipv8/community.py#L45-L46

https://github.com/Tribler/py-ipv8/blob/6eac51d611ab6e06b54622d5f9ab57782dd57a23/ipv8/community.py#L63-L64

**Comment by qstokkink** [comment]
What should be changed?

**Comment by xoriole** [comment]
The above linked IP address and the associated server has reached the end of life so tracker7 and 8 will need a new home and IP. I'll submit a PR with the updates.

**Comment by qstokkink** [comment]
Alright, I assigned you to the issue. It would be nice if the DNS addresses could remain the same though, for backwards compatibility.
