### ISSUE TITLE
Five seconds to introduction response

### ISSUE THREAD

**Issue by xoriole** [Tribler/py-ipv8#921]
New trackers take 5 seconds to respond to introduction request.

```
tracker8.ip-v8.org ('130.161.119.201', 6528) 5.001364231109619
tracker7.ip-v8.org ('130.161.119.201', 6527) 5.000910043716431
tracker6.ip-v8.org ('130.161.119.215', 6526) 0.012974977493286133
tracker5.ip-v8.org ('130.161.119.215', 6525) 0.015378952026367188
tracker4.ip-v8.org ('131.180.27.162', 6524) 0.008288383483886719
tracker3.ip-v8.org ('131.180.27.162', 6523) 0.006510734558105469
tracker2.ip-v8.org ('131.180.27.161', 6522) 0.06022000312805176
tracker1.ip-v8.org ('131.180.27.161', 6521) 0.00586390495300293
```
https://jenkins-ci.tribler.org/job/pers/job/Test_BootstrapServers_Custom/4/console
Here, `tracker7` and `tracker8` are new trackers running the latest `master` while the other trackers run much older version before the reference commit below. Since trackers were not up-to-date, the issue wasn't detected by the Jenkins job.

Looking into the code, adding prefix listener on community seems to be a time expensive task:
https://github.com/Tribler/py-ipv8/blob/487c4a00ce3e2fedb5603c399162a3a23d16e3c8/ipv8/community.py#L74-L75

Reference commit: https://github.com/Tribler/py-ipv8/commit/487c4a00ce3e2fedb5603c399162a3a23d16e3c8

Note: DNS entry for `tracker7` and `tracker8` is set locally on the test node. The public DNS still point to the old server.

**Comment by qstokkink** [comment]
The time of 5 seconds stems from the requests timing out after 5 seconds: this is when the boostrap script deems the server unreachable.

**Comment by qstokkink** [comment]
I just tried it out, the `('130.161.119.201', 6528)` and `('130.161.119.201', 6527)` addresses are unreachable.

**Comment by qstokkink** [comment]
Just to be sure I also printed the time for the 2 expensive statements to complete. Which leads to the following measurements:

```
2.4318695068359375e-05 seconds
2.288818359375e-05 seconds
5.14984130859375e-05 seconds
3.170967102050781e-05 seconds
``` 

Nothing in the order of 5 seconds.

The only thing broken appears to be the port mapping and/or firewall settings of `('130.161.119.201', 6528)` and `('130.161.119.201', 6527)`.

**Comment by qstokkink** [comment]
With some help from @xoriole and @kozlovsky: this is due to the prefix mapping limiting the incoming packets to the fake tracker prefix instead of receiving all packets.
