### ISSUE TITLE
Add external bootstrap server inject script

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#946]
We can use bootstrap servers from external parties in our stack. We already have lazy resolution of DNS names, external mechanisms can use the exact same method.

Note that external bootstrap servers have different protocols, so these will have to be modularized.

Proposed design:

 - A bootstrap script per external protocol in a (new) `ipv8.bootstrap` module.
 - Add a bootstrap manager in this (new) `ipv8.bootstrap` module.
 - Extend `Community.bootstrap()` to call on the (new) bootstrap manager with a `service_id` (the community prefix).
 - Add bootstrap module configuration to the `/ipv8/configuration.py` file.

Possible hurdles:

 - Bootstrapped peers need to reuse the port they received from the external bootstrap server or face bouncing off the NAT or firewall layers. Without resolution, this means the same port will serve two protocols (which can lead to nasty errors).
 - [Thanks @devos50] These capabilities most likely require additional libraries/dependencies to be added. We want each module to have conditional imports.

The interface custom scripts should fill, would be the following:

```python
class Bootstrapper(ABC):
    """
    A script to connect to external bootstrapping resources, using external hardware.

    When not to crash:
     - Loading this module file when missing dependencies.
     - Initializing a subclass when the service is unavailable (return ``False``).
     - Failing to retrieve peers for a service (return an empty iterable, e.g. ``[]``).

    When to crash:
     - Initializing this module subclass when missing dependencies.
    """

    @abstractmethod
    def initialize(self, overlay: Overlay) -> bool:
        """
        Start connecting to this bootstrapping service. Don't perform any network traffic in ``__init__``!

        :param overlay: the network overlay to initialize for.
        :returns: whether the initialization was successful.
        """
        pass

    @abstractmethod
    async def get_addresses(self, overlay: Overlay, timeout: float) -> Iterable[Address]:
        """
        Return some IPv8 addresses (if available) from this bootstrapping service.
        These addresses should be walkable (not blocked by a NAT or firewall).

        :param overlay: the network overlay to get peers for.
        :param timeout: the maximum time we wish to wait until we get any result (i.e. an empty list).
        :returns: the addresses for the given service_id.
        """
        pass

    @abstractmethod
    def keep_alive(self, overlay: Overlay) -> None:
        """
        Periodically called to keep this bootstrap connection alive.

        :param overlay: the network overlay to keep alive.
        """
        pass

    @abstractmethod
    def blacklist(self) -> Iterable[Address]:
        """
        Returns the blacklisted addresses for this Bootstrapper.
        """
        pass
```

**Comment by qstokkink** [comment]
We will be needing a body of scripts to communicate with external bootstrapping nodes using their respective protocols.

Delving into all available options and protocol specifications is a bit much to handle for a single person. Therefore, I invite anyone with a passing interest in this to create and contribute their scripts for their favorite external protocol 😃

**Comment by devos50** [comment]
Hmm, adding bootstrapping capabilities using IRC (specifically the free.net servers) would be interesting. I will consider implementing it if I find some time during the upcoming holiday 👍 

Another hurdle is that these capabilities most likely require additional libraries/dependencies to be added. We probably want to have conditional imports here, and disable the bootstrap method if its dependencies cannot be imported.

**Comment by qstokkink** [comment]
Cool, thanks. I'll also add that hurdle in the O.P.

Since bootstrap methods have to be explicitly loaded from the configuration, I do think that crashing on a failed module load is appropriate though.

**Comment by qstokkink** [comment]
Once the basic infrastructure is available I'll look into hooking in Bittorrent DHT bootstrap nodes, perhaps to accompany the initial PR.
