### ISSUE TITLE
How to extend the "Printing Known Peers" example to peers running on different nodes

### ISSUE THREAD

**Issue by VigneshSP94** [Tribler/py-ipv8#971]
I'm trying to create a simple p2p networking following the [tutorial ](https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial/#printing-the-known-peers), running it as it is works fine, but extending it to run on two different VMs not working (something that I'm doing wrong).

In the example script, we create two peers and the peers finds each other with in the system. I removed the for loop given in the script and made it to start only one peer.

```
import os
from asyncio import ensure_future, get_event_loop

from ipv8.community import Community
from ipv8.configuration import ConfigBuilder, Strategy, WalkerDefinition, default_bootstrap_defs
from ipv8_service import IPv8


class MyCommunity(Community):
    #community_id = os.urandom(20)
    community_id = b'xxxxxxxxxxxxxxxxxxxx'

    print(community_id)

    def started(self):
        async def print_peers():
            print("dei peers da", self.get_peers())
            print("I am:", self.my_peer, "\nI know:", [str(p) for p in self.get_peers()])

        # We register a asyncio task with this overlay.
        # This makes sure that the task ends when this overlay is unloaded.
        # We call the 'print_peers' function every 5.0 seconds, starting now.
        self.register_task("print_peers", print_peers, interval=5.0, delay=0)


async def start_communities():
    #for i in [1, 2]:
        builder = ConfigBuilder().clear_keys().clear_overlays()
        builder.add_key("my peer", "medium", f"ec2.pem")
        builder.set_address('192.168.56.102')
        builder.set_port(9000)
        builder.set_log_level("DEBUG")
        # We provide the 'started' function to the 'on_start'.
        # We will call the overlay's 'started' function without any
        # arguments once IPv8 is initialized.
        builder.add_overlay("MyCommunity", "my peer", [WalkerDefinition(Strategy.RandomWalk, 10, {'timeout': 3.0})],
                            default_bootstrap_defs, {}, [('started',)])
        await IPv8(builder.finalize(), extra_communities={'MyCommunity': MyCommunity}).start()
        #await IPv8(builder.finalize()).start()


ensure_future(start_communities())
get_event_loop().run_forever()
```

I run this script on two different servers and they do not find each other. Is what I'm doing is the right way to get started?
Any direction on how to get going with this will be very helpful.

Thanks.

**Comment by qstokkink** [comment]
With "two different servers" do you mean two different physical machines or two VMs on the same physical machine?

Also, unless you have a very specific network setup, you can remove `builder.set_address('192.168.56.102')`.

**Comment by VigneshSP94** [comment]
Two VMs running in the same host, with two interfaces. One NAT and another is Host-Only. I have set the address thinking that it will utilise the host-only interface to find peers.

**Comment by qstokkink** [comment]
Ah, I was afraid that would be the setup. Whereas [our NAT puncturing protocol](https://link.springer.com/content/pdf/10.1007/978-3-642-20798-3_1.pdf) works quite well for different physical machines over the Internet, we don't support your type of local network setup out-of-the-box quite yet. You need an extra setup step for this.

You would need a process running on your host (I assume this is `192.168.56.102`) that runs the [tracker_plugin.py](https://github.com/Tribler/py-ipv8/blob/master/scripts/tracker_plugin.py) script to perform connection brokering. Each process would then have to change the following line the builder setup:

```python
builder.add_overlay("MyCommunity", "my peer", [WalkerDefinition(Strategy.RandomWalk, 10, {'timeout': 3.0})],
                    default_bootstrap_defs, {}, [('started',)])
```

to

```python
from pyipv8.ipv8.configuration import Bootstrapper, BootstrapperDefinition, DISPERSY_BOOTSTRAPPER

bootstrap_config = DISPERSY_BOOTSTRAPPER['init']
bootstrap_config['ip_addresses'].append(('192.168.56.102', 8090))  # 8090 is the tracker_plugin default port
custom_bootstrap_defs = [BootstrapperDefinition(Bootstrapper.DispersyBootstrapper, bootstrap_config)]
builder.add_overlay("MyCommunity", "my peer", [WalkerDefinition(Strategy.RandomWalk, 10, {'timeout': 3.0})],
                    custom_bootstrap_defs, {}, [('started',)])
```

**Comment by VigneshSP94** [comment]
@qstokkink thanks for your humble help, it worked.

**Comment by qstokkink** [comment]
You're welcome. Have fun playing around 👍 

With a little luck, in the near future #972 will allow for your type of network setup without using any additional process.

Anyway, I assume that answers your question and I'll close this issue for now. Feel free to reopen this issue or open another one if you have further questions.
