### ISSUE TITLE
Add documentation for advanced DiscoveryStrategy use

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#979]
This documentation should include the following.

Configuring Peer discovery:
 - A pointer to the basics of DiscoveryStrategies.
 - How the `RandomWalk` works and when to use it.
 - How the `EdgeWalk` works and when to use it.
 - How the `RandomChurn` works and when to use it.
 - How to parameterize the walk sizes. The default node degree (20-30) makes sense for most use cases, see for example **The Role of Network Topology for Distributed Machine Learning** by Giovanni Neglia, Gianmarco Calbi, Don Towsley and Gayane Vardoyan. Add notes on creating a new `Network()` when mixing with communities of unequal parameters.
 - Caution on combining node removal strategies.

Convergence of the connected Peers:
 - ~~How the Network class actually works and when peers are added, hooking into the [peer discovery basics documentation](https://py-ipv8.readthedocs.io/en/latest/basics/peer_discovery/).~~ *EDIT: Out of scope.* Add a note on sharing peers between communities.
 - ~~How the DiscoveryCommunity consolidates peers and how blocking introduction requests and responses balances peers over communities.~~ *EDIT: Out of scope.*

**Comment by qstokkink** [comment]
This should also integrate the [everything-you-need-to-know-about-overlay-scaling paper](https://www.usenix.org/legacy/publications/library/proceedings/nsdi04/tech/full_papers/shen/shen_html/index.html) (more formally know as **Structure Management for Scalable Overlay Service Construction** by Kai Shen).

**Comment by qstokkink** [comment]
[Failed attempt] I attempted to start by explaining the `Network` class. However, it became apparent that knowing about walkers and peer discovery is a prerequisite to understand the `Network`. Essentially, this old Dispersy documentation needs to be rehashed to fit IPv8 in order to understand the `Network`: https://dispersy.readthedocs.io/en/devel/system_overview.html#peer-selection

**Comment by qstokkink** [comment]
Looking at this again: the basics of #977 should really be written before we jump into the advanced stuff. In essence, this documentation is really an extension of #977 for enthusiasts. I'll put this on hold until that is done.

**Comment by qstokkink** [comment]
With #1027 merged, this can be taken off "on hold".

**Comment by qstokkink** [comment]
Ok, text containing heavy statistical analysis and code is not going to cut it to build intuition for new readers. Having `.gif` images that show how networks evolve is probably going to be much easier to digest. A movie/gif says more than a 1000 words after all.


For example, how long does it take for information to go from node 1 to node 2 in an (a) line topology, (b) ring topology or (c) random regular graph:

![networks](https://user-images.githubusercontent.com/3630389/129000996-491ebd74-ec70-490c-b0c4-70171a6b3fa6.png)

[Of course, the image would have to contain more nodes as the random regular graph looks a bit like a fully connected graph now.]

Another example, seeing what happens when you set your Community `max_peers` equal to your walk's `target_peers`:

![targetpeers](https://user-images.githubusercontent.com/3630389/129001206-d365f395-91c1-4bef-a42f-f908470b6b3a.png)

This should scream: "Looks like a line; not good!"

**Comment by qstokkink** [comment]
There is of course an alternative to explaining this ourselves and that is to just point at existing books on this topic. For example, [slide 20 of the chapter 2 slides for "Introduction to Parallel Computing" by Grama, Gupta, Karypis and Kumar](https://www-users.cse.umn.edu/~karypis/parbook/Figures/chap2.ppt) perfectly lists the diameters of various network constructions. Offering free courses on parallel processing and distributed systems might be a bit too much for our documentation's scope..

**Comment by drew2a** [comment]
FYI: the link [slide 20 of the chapter 2 slides for "Introduction to Parallel Computing" by Grama, Gupta, Karypis and Kumar](https://www-users.cse.umn.edu/~karypis/parbook/Figures/chap2.ppt) is broken

![image](https://user-images.githubusercontent.com/13798583/136013766-f554bec2-4e51-47b5-ab16-8dc38b034ef8.png)

**Comment by qstokkink** [comment]
Some backup links for network diameters:

- Page 78: https://books.google.nl/books?id=iNQLBwAAQBAJ&lpg=PA85&dq=Introduction%20to%20Parallel%20Computing%20diameter&pg=PA78#v=onepage&q=Introduction%20to%20Parallel%20Computing%20diameter&f=false

- Page 44: https://books.google.nl/books?id=B3jR2EhdZaMC&lpg=PA43&dq=Introduction%20to%20Parallel%20Computing%20diameter&pg=PA44#v=onepage&q=Introduction%20to%20Parallel%20Computing%20diameter&f=false

I would've loved to link to Wikipedia for further reading, but their explanation of network diameter is.. a bit short, to say the least: https://en.wikipedia.org/wiki/Network_science#Diameter_of_a_network 🤔 Wikipedia has a lot of text on network science, but very little tangible information to really explain the spread of data in different types of networks.

**Comment by synctext** [comment]
Fitting 2 years of distributed systems master courses into a tutorial is probably not what we want. Simple rules: Don't invent your own crypto, don't build your own overlay, and eat your daily vegetables.

Would recommend the use a simple example as the opening argument.  _Creating network topologies is difficult business. When you are connected to 25 others peers there might still probability of 1 in a _million_ that you connectivity completely breaks in a given day. However, if you have a network of 1 million peers, it might break into or more partitions are you have a complete system meltdown._

On a general level, we have easily 9 comments on a documentation issue. Somehow we have a collective blockage to actually add something to the documentation. Generating it from source code headers is probably not the solution, but its a strange pattern with multiple developers.

**Comment by synctext** [comment]
Future ToDo, after 2022 summer. The AllChannels content dissemination community test has "unreasonable effectiveness". By **plotting 1000 lines** into a single plot a healthy experiment or fault shows up. Many bugs have been shows to exist using this approach. Its basically an end-to-end performance analysis, peer neighbourhood bias, and unhealthy overlay in general.
![image](https://user-images.githubusercontent.com/325224/155896485-16956d03-40ca-4ed1-bd12-504dc00639dc.png)


Read the entire scientific test here: https://dl.ifip.org/db/conf/networking/networking2013/ZeilemakerCP13.pdf

**Comment by qstokkink** [comment]
I absolutely agree that looking at message synchronization is useful, but it does not capture network fragility/robustness (which is also one of the main points of this documentation issue). For example, the graph you just posted might have been the result of the following star network (credit to the market experiments);

<img src="https://user-images.githubusercontent.com/3630389/155897928-a890b65b-9e20-4c17-8774-30d92d929373.png" data-canonical-src="https://user-images.githubusercontent.com/3630389/155897928-a890b65b-9e20-4c17-8774-30d92d929373.png" width="300" />

Suppose the center peer (1) either left the network or became malicious: this would cause system meltdown. You would've never known if you _only_ looked at the message synchronization graph. Therefore, I wouldn't depend _solely_ on message synchronization.

This is a very real and insidious issue. [We had a similar (albeit a bit more complex) situation when we added reciprocity-based peer discovery:](https://github.com/Tribler/tribler/issues/2894#issuecomment-469326503)

> Post-mortem2: load-balancing needs to be maintained when doing non-random walks! Trust introduces a strong bias. Destructive and leads to overloading of highly-trusted nodes in a power-law setting or complete neglect of low-trust nodes.

**Comment by synctext** [comment]
you're right! One of the 25 AllChannel figures was "load" for each peer. With again 1000 lines it's easy to spot outliers for both extremes.

**Comment by xoriole** [comment]
Some graphs of `Experiment_AllChannel+Channelcommunity_next` from archive of `2016_09_24`
![bl_reuse_1](https://user-images.githubusercontent.com/1442867/155969334-29412d12-3f1d-47ed-a5b4-f84973b278e4.png)
![bl_skip_1](https://user-images.githubusercontent.com/1442867/155969341-00f0b65c-2a96-4d09-a518-97b9a2b3ac23.png)
![dropped_diff](https://user-images.githubusercontent.com/1442867/155969342-15b502af-8f81-4303-82dd-7c2a50eb46b7.png)
![dropped](https://user-images.githubusercontent.com/1442867/155969346-ec24da85-4013-480d-b503-dffb4e67a924.png)
![incomming_connections_1](https://user-images.githubusercontent.com/1442867/155969348-fca05df1-4c0f-45b5-afae-a69301537bf9.png)
![incomming_connections_2](https://user-images.githubusercontent.com/1442867/155969350-65c89912-537e-4d9e-be39-673917706ffe.png)
![incomming_connections_3](https://user-images.githubusercontent.com/1442867/155969352-3499e1a6-43e5-4bb1-aa41-7eabecf36c77.png)
![rchars](https://user-images.githubusercontent.com/1442867/155969353-e6ad98f3-d73a-4402-a65f-46e987fe4f7f.png)
![readbytes](https://user-images.githubusercontent.com/1442867/155969356-4a00ef27-da2c-4bba-8ad0-73ebd07b2ad1.png)
![received_diff](https://user-images.githubusercontent.com/1442867/155969357-a1620123-dfeb-4f94-97c9-0a90754a019f.png)
![received](https://user-images.githubusercontent.com/1442867/155969359-e932277b-8a66-408e-a581-f6024e2f2c3a.png)
![rsizes](https://user-images.githubusercontent.com/1442867/155969362-194799fd-6631-446e-a473-f291e6feea20.png)
![send_diff](https://user-images.githubusercontent.com/1442867/155969363-a57eccda-4195-4966-8cef-3ef1861cdff2.png)
![send](https://user-images.githubusercontent.com/1442867/155969366-7a357f29-9556-4f4a-a33e-573d780e6bd3.png)
![stimes](https://user-images.githubusercontent.com/1442867/155969368-80ccde39-5cf6-4d13-82c9-a69065d7d11c.png)
![total_connections_1](https://user-images.githubusercontent.com/1442867/155969369-5b44dffa-e874-4e5d-809a-0ebfeef0003f.png)
![total_connections_2](https://user-images.githubusercontent.com/1442867/155969372-517bbf0c-eedd-47b3-893d-957ea3114891.png)
![total_connections_3](https://user-images.githubusercontent.com/1442867/155969373-ad99cc43-e1b9-46fe-a499-ea194a5ef629.png)
![total_records](https://user-images.githubusercontent.com/1442867/155969376-269b80e9-0bd8-4994-807b-8b022f320038.png)
![type_connections_1](https://user-images.githubusercontent.com/1442867/155969377-f2baf274-b724-460b-afe4-916f688614bb.png)
![type_connections_2](https://user-images.githubusercontent.com/1442867/155969378-3a707554-bc8a-437d-afd0-9c6daa3053b5.png)
![type_connections_3](https://user-images.githubusercontent.com/1442867/155969379-b2f27af4-6286-469c-8e0e-f62a0c6dd30a.png)
![utimes](https://user-images.githubusercontent.com/1442867/155969380-d4881a06-2e3a-4d24-a5fa-5e8fad5bad4e.png)
![wchars](https://user-images.githubusercontent.com/1442867/155969383-461ef81a-4b7c-4beb-a89e-db356c4d5ab5.png)
![writebytes](https://user-images.githubusercontent.com/1442867/155969387-c3a7c1a3-5d19-4c10-a4fc-39594c1818d4.png)

**Comment by qstokkink** [comment]
I see that this issue is moving away from IPv8 documentation and moving into Gumby experiment design. There should be a separate issue for the Gumby experiment discussion in the Gumby repository instead (+1 to whomever creates that issue).

**Comment by devos50** [comment]
@qstokkink I made one: https://github.com/Tribler/gumby/issues/513 👍

**Comment by qstokkink** [comment]
In order to finally get this documentation out, I placed the nitty gritty details of peer convergence out of scope for this issue (updated O.P.).
